### ISSUE TITLE
Listener on iOS simulator not triggered sometimes

### ISSUE THREAD

**Issue by rgommezz** [rgommezz/react-native-offline#10]
Follow up the thread on: https://github.com/facebook/react-native/issues/8615
A couple of potential workarounds have been proposed.

Works fine on real devices

**Comment by pongponglau** [comment]
@rauliyohmc, thanks for your advice. react-native-offline works great in Android (i have no iphone with me now, so will test it later).

I find that if i run the thunk actioncreator function in componentDidMount when there is no network, thunk return function will not be called when the network is resumed. Besides, may i ask if network detection also works correctly when the real device is connected to either wifi or 4G but there is no real network (e.g. in the lift of a high-rise building).

Thank you very much for your advices again.
