### ISSUE TITLE
Windows 10 compatibility

### ISSUE THREAD

**Issue by chrisreactnative** [rgommezz/react-native-offline#101]
Is this library compatible with windows? I noticed it was here (https://js.coach/react-native-offline?collection=React+Native&compatibility=Windows) when filtering results showing Windows compatibility, but it says in the docs it's compatible on iOS and Android, no mention of Windows?

**Comment by rgommezz** [comment]
Hello @chrisreactnative,

I believe it is. This library relies on RN `NetInfo` module to work properly and I see `react-native-windows` provides [its own implementation of it](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative/Modules/NetInfo/NetInfoModule.cs), so you should be good to go. I'll add Windows to the docs
