### ISSUE TITLE
firestore integration? (doc)

### ISSUE THREAD

**Issue by callagga** [rgommezz/react-native-offline#102]
Can react-native-offline offline be used in co-operation with Google's Firestore?  Any documentation/links to how to look further into this?  

**Background**: 

I have used Firestore with react-native and as a beginner it provides a great way to get "offline support" out of the box with it's javascript sdk (via react-native-firestore), and provides the backend datastore too).   The issue I have is I can't control/customize (as far as I know) how to control how the synchronisation occurs after an offline app reconnects, apart from it will just overwrite store once back online.   For example, if I want to ensure an update that is 5 days old but the device just came back online, doesn't overwrite a change from 1 day ago.   

If you happen to know whether react-native-offline can integrate with firestore to solve this?   Or do I really need react-native-offline as part of a roll your own solution including having to create a backend store?

**Comment by rgommezz** [comment]
Hi @callagga,

I haven't used `react-native-firestore`, but it seems both packages serve different purposes. The main goal of this library is to customise your UI based on offline connection and to provide a thin integration layer with redux to store actions offline and re-dispatch them when re-connected. However, it's meant to be for short times of disconnection.

> The issue I have is I can't control/customize (as far as I know) how to control how the synchronisation occurs after an offline app reconnects.

I think Firestore should handle those updates automatically for you. If I were you, I'd open an issue on their repo asking about that matter.
