### ISSUE TITLE
withNetworkConnectivity is always false?  (code attached)

### ISSUE THREAD

**Issue by callagga** [rgommezz/react-native-offline#103]
Hi - I am always getting a network connectivity = false with the below code.   Am I do something wrong here?    Should the "export default withNetworkConnectivity()(AppTest);" line ensure the JSX page should update if the network status changes? 

```
import React, { Component } from 'react';
import { Text, StyleSheet, View, Button } from 'react-native';
import { withNetworkConnectivity } from 'react-native-offline';
import { PropTypes } from 'prop-types';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

class AppTest extends Component {
  constructor(props) {
    super(props);
    this.onPressLearnMore = this.onPressLearnMore.bind(this);
  }
  onPressLearnMore() {
    console.log('onPressLearnMore');
    this.forceUpdate();
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>{this.props.isConnected ? 'Online' : 'Offline'}</Text>
        <Button
          onPress={this.onPressLearnMore} // .bind(this)}
          title="Learn More"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />        
      </View>
    );
  }
}

AppTest.propTypes = {
  isConnected: PropTypes.bool.isRequired,
};

export default withNetworkConnectivity()(AppTest);
```

Versions:

```
react-native --version
react-native-cli: 2.0.1
react-native: 0.55.4

yarn list | grep offline
├─ react-native-offline@3.10.0

```

**Comment by breadadams** [comment]
@callagga [enabling arbitrary loads](https://stackoverflow.com/a/40299837/2553600) in Xcode resolved the issue for me - as the lib is trying to ping an external URL

**Comment by callagga** [comment]
Thanks by the way! This fixed it

**Comment by acomito** [comment]
@breadadams Does this cause a security flaw? I only looked briefly, but saw this guys comment:

> Why is NSAllowsArbitraryLoads set to true? You subvert the purpose of ATS. Also see The most dangerous code in the world: validating SSL certificates in non-browser software. Your software just made the list

https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http/40299837#40299837
