### ISSUE TITLE
module redux-saga/effects not found in haste module map

### ISSUE THREAD

**Issue by hutchy2570** [rgommezz/react-native-offline#109]
Regression which has reintroduced https://github.com/rgommezz/react-native-offline/issues/70

The fix for https://github.com/rgommezz/react-native-offline/issues/104 has reintroduced this issue for those of us not using redux-saga.

**Comment by msardi23** [comment]
+1

**Comment by qasimalbaqali** [comment]
To fix this just add redux-sega as a dependency. `yarn add redux-sega`

**Comment by bkspace** [comment]
:trollface: "redux-sege" => "redux-saga"

**Comment by n0umankhan** [comment]
@qasimalbaqali in which package.json we need to add this as dependency, the project one or inside react-native-offline package file ?

**Comment by qasimalbaqali** [comment]
@n0umankhan I added it to my project, but I'm guessing you could also add it to the react-native-offline dependencies, first I would suggest forking it.

**Comment by n0umankhan** [comment]
@qasimalbaqali Thanks dude after npm i --save redux-saga in my project folder problem is resolved :)

**Comment by hutchy2570** [comment]
Having to install a dependency which I don't _actually_ use isn't really a solution to this.

**Comment by hutchy2570** [comment]
@n0umankhan it doesn't _always_ use this dependency.  It will only use `redux-saga` if you're specifically using the `networkEventsListenerSaga` https://github.com/rgommezz/react-native-offline/blob/master/src/index.js#L17.  Otherwise it won't need to use it.

**Comment by n0umankhan** [comment]
I'm sure myself and others are not specially using that listner

**Comment by macrozone** [comment]
its now a dependency again, so you don't have to install it, but it will be installed for you.
