### ISSUE TITLE
Implementing UI-blocking activity indicator globally when offline

### ISSUE THREAD

**Issue by robreuss** [rgommezz/react-native-offline#112]
I was looking for a tip on how to use withNetworkConnectivity (without Redux) to present a View that blocks the UI and includes an activity indicator when there is no network connectivity, without doing so on each screen - that is, to do it on the root view.  For my MVP, I'm keeping things simple and blocking using activity when there is no network available - will add queuing later.  Thanks.

**Comment by rgommezz** [comment]
Hey @robreuss,

You can wrap your root view with `withNetworkConnectivity` and then, inside the render method, return your `OfflineComponent` or your `MainNavigator` based on `isConnected` prop. Something along these lines:

```js
class Root extends React.Component {
  render() {
    const { isConnected } = this.props;
    if (!isConnected) return <OfflineView />
    return <MainNavigator persistenceKey="persistence_key" />
  }
}

export default withNetworkConnectivity()(Root);
```

That will make your app switch to that screen anytime you get offline. 
If you are using React Navigation, to not lose navigation state add a `persistenceKey`.

If you want something more fine-grained, you'd need to listen to `isConnected` prop changes in some lifecycle hook and push/pop the offline view accordingly.

Sorry for my late response.
