### ISSUE TITLE
Error in configuration - isConnected is undefined

### ISSUE THREAD

**Issue by sharathchandramg** [rgommezz/react-native-offline#113]
Hi,
I am facing issues with getting the app running with basic configurations. The app is using

- "react-native": "0.51"
- "react-redux": "^5.0.6",
- "redux": "^3.7.2",
- "redux-persist": "^5.6.11",
- "redux-saga": "^0.16.0"

My app.js is 

```
export default class App extends Component {
  render() {  
    return (
      <Provider store={store}>
        <PersistGate persistor={persistor}>
          <ErrorBoundary>
           
            <RootNavigator ref={
              navigatorRef => {
                NavigationService.setTopLevelNavigator(navigatorRef)
              }
            } />
          </ErrorBoundary>
        </PersistGate>
      </Provider>
    );
  }
}
```

Root navigator wraps all the navigators. I have enclosed this with networkConnectivity

```
let RootNavigator = createSwitchNavigator({

    AuthLoading: AuthLoadingScreen,
    Auth: AuthNavigation,
    App: AppNavigation

}, {
        initialRouteName: "AuthLoading"
    });


RootNavigator = withNetworkConnectivity({
    withRedux: true // It won't inject isConnected as a prop in this case
  })(RootNavigator);

```

The root reducer is working fine, 

```
const AppReducer = combineReducers({
    LoginReducer: persistReducer(sensiveInfoPersistConfig, loginReducer),
    //.. other reducers
    NetworkReducer : network
});
```

I have updated the store with network middleware

```
function configureStore(initialState) {

  const enhancer = compose(
    applyMiddleware(      
      loggerMiddleware,
      networkMiddleware,
      sagaMiddleware
    )
  );

  const store = createStore(reducer, initialState, enhancer);
  sagaMiddleware.run(rootSaga);

  return store;
  
}
let store = configureStore({});
export default store;
```

The entry point of sagas has

```

export default function* rootSaga() {
    yield all([
        watchUserOnBoarding(),
        //all other wathers
        fork(networkEventsListenerSaga, { timeout: 2000, checkConnectionInterval: 20000 })
    ]);
}
```

However I am getting an error 
```

Cannot read property 'isConnected' of undefined
<unknown>
    createNetworkMiddleware.js:37:12
Object.dispatch
    redux-logger.js:1:7806
Object.persist
    persistStore.js:105:12
persistStore
    persistStore.js:109:12
<unknown>
    App.js:22:18
loadModuleImplementation
    require.js:191:4
guardedLoadModule
    require.js:138:11
_require
    require.js:118:2
<unknown>
    index.js:2
loadModuleImplementation
    require.js:191:4

```

What am i missing? Is there any sample repo which I can look for further guidance?

**Comment by sharathchandramg** [comment]
I was using a different name for network in the reducer which was causing this issue
Saw this piece of code. 

```
const { isConnected, actionQueue } = getState().network;
```

Updated my reducer to return network

**Comment by sea930320** [comment]
Hi, I got the same Error
[http://prntscr.com/n60krk](url)

- "react-native": "0.55.4"
- "react-redux": "^6.0.1",
- "redux": "^4.0.0",
- "redux-persist": "^5.9.1",
- "redux-thunk": "^2.3.0",

Here is my code:

- Setup.js (Root Comonent)

`import React, { Component } from "react";
import { Provider } from "react-redux";
import { StyleProvider } from "native-base";
import { NetworkProvider } from 'react-native-offline';
import { Content } from 'native-base'

import Parent from "../Parent";
import configureStore from "./configureStore";
import getTheme from "../theme/components";
import variables from "../theme/variables/commonColor";
import LoadingComponent from '../screens/Secured/BaseComponent/loading'

export default class Setup extends Component {
  constructor() {
    super();
    this.state = {
      isLoading: true,
      store: configureStore(() => this.setState({ isLoading: false }))
    };
  }

  render() {
    if (this.state.isLoading) return (
      <Content>
        <LoadingComponent />
      </Content>
    );
    return (
      <StyleProvider style={getTheme(variables)}>
        <NetworkProvider>
          <Provider store={this.state.store}>
            <Parent />
          </Provider>
        </NetworkProvider>
      </StyleProvider>
    );
  }
}
`


- configureStore.js

`import devTools from "remote-redux-devtools";
import {
  createStore,
  applyMiddleware,
  compose
} from "redux";
import thunk from "redux-thunk";
import {
  persistStore,
  persistReducer
} from "redux-persist";
import {
  createNetworkMiddleware,
  offlineActionTypes,
  checkInternetConnection
} from 'react-native-offline';
import storage from 'redux-persist/lib/storage'
import rootReducer from "../reducers";

const networkMiddleware = createNetworkMiddleware({
  queueReleaseThrottle: 200,
});

export default function configureStore(onCompletion) {
  const enhancer = compose(
    applyMiddleware(networkMiddleware, thunk),
    devTools({
      name: "dryforms",
      realtime: true
    })
  );

  const persistConfig = {
    key: 'root',
    storage,
  }

  const persistedReducer = persistReducer(persistConfig, rootReducer)
  let store = createStore(persistedReducer, enhancer);
  persistStore(store, null, () => {
    checkInternetConnection().then(isConnected => {
      store.dispatch({
        type: offlineActionTypes.CONNECTION_CHANGE,
        payload: isConnected,
      });
      onCompletion();
    });
  });

  return store;
}`
