### ISSUE TITLE
Problems with redux-saga 1.0.0-beta

### ISSUE THREAD

**Issue by doomsower** [rgommezz/react-native-offline#120]
In my project I use `redux-saga@1.0.0-beta.1` and `checkConnectionInterval` was not working. Forked generators (`yield fork(netInfoChangeSaga, timeout, pingServerUrl, withExtraHeadRequest);`) were not working.
It took me a while to figure out that there is a conflict between versions of redux-saga.

I fixed it by adding
```json
  "resolutions": {
    "react-native-offline/redux-saga": "^1.0.0-beta.1"
  },
```
to my `package.json`.

For some reason (published `yarn.lock`, `devDependencies`/`dependencies` overlap or whatever)  `react-native-offline` installs `redux-saga@0.16.0`. Probably `"redux-saga": "*"` should be moved from `dependencies` to `peerDependencies`

**Comment by macrozone** [comment]
this is already done and merged, but maybe not released yet? https://github.com/rgommezz/react-native-offline/issues/104

**Comment by doomsower** [comment]
It was reverted by https://github.com/rgommezz/react-native-offline/commit/7aa425e2a5d4ce551ca78e4c65a17694b6ce0881

**Comment by macrozone** [comment]
@doomsower now its a "*"-Version dependency, so your problem should be fixed by that?

Maybe inspect your yarn.lock, there you should see which module requires version 0.16.0

**Comment by macrozone** [comment]
anyway, neither commit seems to have been released, so you might need to set the version to the commit url

**Comment by doomsower** [comment]
I just tried it on a fresh project. Installed `redux-saga@1.0.0-beta.1`, then installed `react-native-offline`, `3.11.1` is the latest on npm and is latest commit here. `react-native-offline` brings `redux-saga@0.16.0` with it.

Anyway, for now I got it fixed with yarn resolutions.

**Comment by macrozone** [comment]
@doomsower just tried it and can confirm, it does not work properly, also need to use yarn resolutions
