### ISSUE TITLE
Can I use without saga? 

### ISSUE THREAD

**Issue by Ann1995** [rgommezz/react-native-offline#149]
I was reading the documentation but it didn't work out for me
maybe there is an example?

**Comment by rgommezz** [comment]
Hey @Ann1995,

What features do you intend to use and what step in particular did you get stuck with?

For the minimum usage, which is to have a network state in your Redux store you have to follow the next steps:

1. Wiring up the reducer
2. Without sagas, you'd use [ReduxNetworkProvider](https://github.com/rgommezz/react-native-offline#reduxnetworkprovider)
3. Use react-redux `connect` function to access to the network state inside your components.

Those are the steps reflected in the documentation. Maybe is confusing you the step 2? If so, I can better clarify it with a quick PR.

**Comment by Ann1995** [comment]
@rgommezz already figured out, thanks for the quick response!
