### ISSUE TITLE
could not find "store"

### ISSUE THREAD

**Issue by abudahsh** [rgommezz/react-native-offline#151]
I always get this error although i wrapped my component in redux provider
<img width="325" alt="screen shot 2019-01-07 at 8 09 37 pm" src="https://user-images.githubusercontent.com/29312046/50785362-01cd6b00-12b9-11e9-954e-4cd1d6784d96.png">

my code 
`export default class App extends Component {

  render() {

    return (

      <Provider store={store}>

      <ReduxNetworkProvider >

        <WelcomeSwitch />

      </ReduxNetworkProvider>   

      </Provider>

    );
  }
}
`

**Comment by rgommezz** [comment]
Hey @abudahsh,

I set up a redux basic example and wasn't able to reproduce the issue. It could be due to how you are creating the `store`. Could you show me how you are doing that?
This is my dummy working example you could follow as reference:

### Actions

```js
export const addOne = () => ({
    type: 'ADD_ONE',
});
```

### Store and reducer

```js
import { createStore, combineReducers } from 'redux'
import { reducer as network } from 'react-native-offline';

const initialCount = 0;

const rootReducer = combineReducers({
    count: (state = initialCount, action) => {
        if (action.type === 'ADD_ONE') {
            return state + 1;
        }
        return state;
    },
    network,
});

const store = createStore(rootReducer);
export default store;
```

### Components

```js
import React from 'react';
import { Provider, connect } from 'react-redux';
import { StyleSheet, Text, View, Button } from 'react-native';
import { ReduxNetworkProvider } from 'react-native-offline';
import store from './store';
import { addOne } from './actions';

let Root = class Root extends React.Component {
    handleButtonPress = () => {
        this.props.addOne();
    };

    render() {
        return (
            <ReduxNetworkProvider>
                <View style={styles.container}>
                    <Button title="Add One" onPress={this.handleButtonPress} />
                    <Text>{this.props.count}</Text>
                </View>
            </ReduxNetworkProvider>
        );
    }
}

Root = connect((state) => ({
    count: state.count,
}), {
    addOne,
})(Root);

export default class App extends React.Component {
    render() {
        return (
            <Provider store={store}>
                <Root />
            </Provider>
        );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by gams95** [comment]
@rgommezz any example on how to implement ReduxNetworkProvider with PersistGate from redux-persist?

**Comment by ghorbani-m** [comment]
I have the same error too.

**Comment by gams95** [comment]
@ghorbani-m @abudahsh Are u guys using React-Navigation by any chance? I have this error when my component is initiated by createSwitchNavigator()

**Comment by ghorbani-m** [comment]
@gams95 Yes, I have used the "createSwitchNavigator" to initiate my App.

**Comment by abudahsh** [comment]
@rgommezz 
Reducer
`
const reducer = combineReducers({

  client: clientReducer,

  user: userReducer,

  products: productReducer,

  categories: categoriesReducer,

  vendors: vendorsReducer,

  news: newsReducer,

 cart: cartReducer,

  subCategoryProducts: subCategoryProductsReducer,

  network

});

export default reducer;

`

Store
`
import { createStore, applyMiddleware, compose } from "redux";

import { composeWithDevTools } from "remote-redux-devtools";

import { createNetworkMiddleware } from "react-native-offline";

import reducer from "./reducer";

import thunk from "redux-thunk";

const networkMiddleware = createNetworkMiddleware();

export default (store = createStore(

  reducer,


  /* preloadedState, */ composeWithDevTools(

    applyMiddleware(networkMiddleware, thunk)

  )

));

`

App.js

`
import React, { Component } from "react";

import { Provider, connect } from "react-redux";

import store from "./redux/store";

import { NetworkProvider , ReduxNetworkProvider} from "react-native-offline";

import WelcomeSwitch from "./navigators";

export default class App extends Component {

  render() {

    return (

      <Provider store={store}>

      <ReduxNetworkProvider >

        <WelcomeSwitch />

      </ReduxNetworkProvider> 
  
      </Provider>

    );

  }

}

`

WelcomeSwitch is a React-Navigation switch navigator

**Comment by souvik-ghosh** [comment]
> Hey @abudahsh,
> 
> I set up a redux basic example and wasn't able to reproduce the issue. It could be due to how you are creating the `store`. Could you show me how you are doing that?
> This is my dummy working example you could follow as reference:
> 
> ### Actions
> ```js
> export const addOne = () => ({
>     type: 'ADD_ONE',
> });
> ```
> 
> ### Store and reducer
> ```js
> import { createStore, combineReducers } from 'redux'
> import { reducer as network } from 'react-native-offline';
> 
> const initialCount = 0;
> 
> const rootReducer = combineReducers({
>     count: (state = initialCount, action) => {
>         if (action.type === 'ADD_ONE') {
>             return state + 1;
>         }
>         return state;
>     },
>     network,
> });
> 
> const store = createStore(rootReducer);
> export default store;
> ```
> 
> ### Components
> ```js
> import React from 'react';
> import { Provider, connect } from 'react-redux';
> import { StyleSheet, Text, View, Button } from 'react-native';
> import { ReduxNetworkProvider } from 'react-native-offline';
> import store from './store';
> import { addOne } from './actions';
> 
> let Root = class Root extends React.Component {
>     handleButtonPress = () => {
>         this.props.addOne();
>     };
> 
>     render() {
>         return (
>             <ReduxNetworkProvider>
>                 <View style={styles.container}>
>                     <Button title="Add One" onPress={this.handleButtonPress} />
>                     <Text>{this.props.count}</Text>
>                 </View>
>             </ReduxNetworkProvider>
>         );
>     }
> }
> 
> Root = connect((state) => ({
>     count: state.count,
> }), {
>     addOne,
> })(Root);
> 
> export default class App extends React.Component {
>     render() {
>         return (
>             <Provider store={store}>
>                 <Root />
>             </Provider>
>         );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: '#fff',
>     alignItems: 'center',
>     justifyContent: 'center',
>   },
> });
> ```

@rgommezz 
I am getting the same error.
I tried this code and it's not working. works after removing <ReduxNetworkProvider></ReduxNetworkProvider>

**Comment by MingFaiYau** [comment]
i think it should be the version problem..
i got this error in my old app after updated offline to the latest. 
And after updated redux, the problem solved.

old package ->
"react-native-offline": "^3.15.2",
"react-redux": "^5.0.7",
"redux": "^4.0.0",
"redux-thunk": "^2.2.0"

new package ->
"react-native-offline": "^4.1.2",
"react-redux": "^6.0.0",
"redux": "^4.0.1",
"redux-thunk": "^2.3.0"

**Comment by gams95** [comment]
I have reverted back to the old version for now. Will try to upgrade react-redux and try it with the new version when i have time. Thanks for the feedback.

**Comment by souvik-ghosh** [comment]
Yup, react-redux v5 was causing the problem. Got up and running with v6.

**Comment by cuttlas** [comment]
I'm experiencing this problem, and upgrading react-redux didn't help :)

Versions:
react-native-offline@4.1.2
react-redux@6.0.0
react@16.6.1


React 

store.js
```javascript
import { createStore, applyMiddleware } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";
import thunkMiddleware from "redux-thunk";
import { createNetworkMiddleware } from "react-native-offline";
import root from "../reducers/root";

const finalCreateStore = composeWithDevTools(
  applyMiddleware(createNetworkMiddleware(), thunkMiddleware)
)(createStore);
const store = finalCreateStore(root);

export default store;
``` 

app.js
```javascript
import React from "react";
import {
  View,
  Dimensions,
  NetInfo,
  BackHandler,
  StatusBar
} from "react-native";
import { Router, Route } from "react-router-native";
import { Provider } from "react-redux";
import { ThemeContext, getTheme } from "react-native-material-ui";
import { ReduxNetworkProvider } from "react-native-offline";
import store from "./stores";
import styles from "./styles";

class App extends React.Component {
  render() {
    return (
      <Provider store={store}>
        <ReduxNetworkProvider>
          <ThemeContext.Provider value={getTheme(uiTheme)}>
            <Router history={history}>
              <View
                style={styles.container}
              >
                <Route exact path="/" component={Intro} />
                <Route path="/signup" component={Signup} />
                <Route path="/login" component={Login} />
                <Route path="/board" component={Main} />
              </View>
            </Router>
        </ThemeContext.Provider>
       </ReduxNetworkProvider>
      </Provider>
    );
  }
}

export default App;
```

Am I doing anything wrong?

**Comment by MayaZeinalova** [comment]
@cuttlas Have you find a solution? I'm using react-native-router-flux and also have one routing file which i'm importing to App.js file and wrap with ReduxNetworkProvider and  Provider .

 The implementation method you showed is not suitable for this task @rgommezz because i have a lot of reducers and actions . So what is solution ?

**Comment by nabinkumarn** [comment]
There seems to be a problem with "react-native-offline": "^4.3.0" and  "react-redux": "6.0.1".
So I downgraded react-redux to 6.0.0 and issue is solved for now

**Comment by zMaiia** [comment]
@nabinkumarn    
 "react-native-offline": "4.3.0",
 "react-native-router-flux": "4.0.6"
 "react-redux": "6.0.0",

i have  6.0.0 version of react-redux

**Comment by euroclydon37** [comment]
I'm running into this as well with the following.

```js
{
  "react-redux": "6.0.0",
  "react-native-offline": "4.3.0",
  "redux": "4.0.1",
  "react": "16.8.3",
}
```

**Comment by zMaiia** [comment]
i've create test empty app and used pointed versions of packages 

  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.2",
    "react-native-offline": "4.3.0",
    "react-native-router-flux": "^4.0.6",
    "react-redux": "6.0.0",
    "redux": "4.0.1"
  },

all dependencies that I have.

App.js

import React, { Component } from 'react';
import { Provider } from 'react-redux';
import Router from './Router';
import initialState from './store';
import { ReduxNetworkProvider } from 'react-native-offline';

const store = initialState();

export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <ReduxNetworkProvider>
          <Router />
        </ReduxNetworkProvider>
      </Provider>
    );
  }
}

store.js


import { applyMiddleware, createStore } from 'redux';
import reducers from './reducers';
import { createNetworkMiddleware } from 'react-native-offline';

const networkMiddleware = createNetworkMiddleware();

export default initialState => {
    const finalCreateStore = applyMiddleware(networkMiddleware)(createStore);
    const store = finalCreateStore(reducers);

    return store;
}


Router.js


import React, { Component } from 'react';
import { Router, Scene } from 'react-native-router-flux';
import { Home } from './scenes/home';


class RouterComponent extends Component {
    render() {
        return (
            <Router
                hideNavBar
            >
                <Scene keys="root" hideNavBar>
                    <Scene
                        hideNavBar
                        key="home"
                        component={Home}
                    />
                </Scene>
            </Router>
        )
    }
}

export default RouterComponent;

home.js


import React from "react";
import ReactNative, {
    View,
    StyleSheet,
    Text,
    SafeAreaView
} from "react-native";
import { Actions } from 'react-native-router-flux';



class Home extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
        }
    }


    render() {
        return (
            <View style={style.page}>
                <Text>Home</Text>
            </View>
        );
    }
}

const style = StyleSheet.create({
    page: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    }
});



export { Home };


reducers/ index.js


import { combineReducers } from 'redux';
import { reducer as network } from 'react-native-offline';

const reducers = combineReducers({
    network
});

export default reducers;




I still get the same error...

**Comment by stereu** [comment]
Same error here with react-redux 7.0.4 and react-navigation.

**Comment by rockyhuber** [comment]
Me too.

**Comment by imardini98** [comment]
I'm having the same error. Any help please?

**Comment by cuttlas** [comment]
What it worked for me is removing the react-redux dependency of my own project.

npm un react-redux
npm i react-native-offline

This way you make sure there's only one version of react-redux.

**Comment by jsina** [comment]
I've actually used @cuttlas workaround and it's worked, so @rgommezz is it correct to remove react-redux dependency from project?

**Comment by songoten28** [comment]
My  "react-redux": "^7.1.0" and got same issues

**Comment by Chandrakala-B** [comment]
I always get this error.
![Simulator Screen Shot - iPhone X - 2019-08-16 at 09 01 25](https://user-images.githubusercontent.com/46925824/63146377-5d629280-c018-11e9-9c1f-bc27962fad54.png)

My App.js file
render() {
		return (
			<Provider store={store}>
				<PersistGate loading={null} persistor={persistor}>
				<ReduxNetworkProvider>
					<AppContainer
						ref={navigatorRef => {
							NavigationService.setTopLevelNavigator(navigatorRef);
						}}>
					</AppContainer>
				</ReduxNetworkProvider>
				</PersistGate> 
			</Provider>
		);
	}

Could you please help me on this to resolve.

**Comment by matinzd** [comment]
Stil have error on`react-redux v7.1.1 `

**Comment by LeviYoder2112** [comment]
The error that was coming up for me wasn't the same as you all mention, but it was solved by @cuttlas solution. Initially, I was unable to use the NetworkConsumer component, my app would crash on loading with the error "NetworkConsumer component needs to be contained in a NetworkProvider component".
The NetworkConsumer component was definitely contained within a ReduxNetworkProvider, though:

`export default function App() {
  return (
    <Provider store={store}>
      <ReduxNetworkProvider>
        <PersistGate loading={null} persistor={persistor}>
          <TabNavigator />
        </PersistGate>
      </ReduxNetworkProvider>
    </Provider>
  );
}`

If I used NetworkProvider instead of ReduxNetworkProvider, my app didn't crash and that error stopped bring thrown.
Hours of debugging and googling go by, and then I tried what @cuttlas said. I npm uninstalled redux, react-redux, and react-native-offline, then I reinstalled react-native-offline, and now everything works with ReduxNetworkProvider.
Not sure what the version of redux was before I uninstalled, but redux-native was version 7.1.1.

Figured that might help someone out there.

**Comment by Milankorangi** [comment]
im getting this error
![Simulator Screen Shot - iPhone XR - 2019-09-26 at 14 06 01](https://user-images.githubusercontent.com/18266069/65671368-d5d06080-e066-11e9-8fc0-7c7c936c58c6.png)

**Comment by VincentCATILLON** [comment]
For all people having this error, be careful to have only one version of `react-redux` in your dependencies lock file (`yarn.lock` or `package-lock.json`).

Installing this (amazing) package added another version of `react-redux` than the one in my `package.json`, and turned into this issue.

Hope this help 👍

**Comment by mbrucher** [comment]
Noticed a similar problem, solved it with @VincentCATILLON solution + made sure that my package.json had the same version.

**Comment by dkoprowski** [comment]
> For all people having this error, be careful to have only one version of `react-redux` in your dependencies lock file (`yarn.lock` or `package-lock.json`).
> 
> Installing this (amazing) package added another version of `react-redux` than the one in my `package.json`, and turned into this issue. So, I fixed it setting `react-redux` to a fixed version (to only have one version resolved).
> 
> Hope this help 👍

Thank you for this answer. 
This works but in my opinion this is not error safe for future development of the app.
I fixed versions of packages to
```
"react-redux": "7.1.3",
"react-native-offline": "5.2.0",
```
I had react-redux in version `7.1.0` previously but offline package kept installing it's own version `7.1.3` then I've added this version to whole app. If I wouldn't freeze react-native-offline version I assume it would update it's dependencies in future updates and crash the app again.
