### ISSUE TITLE
Usable without components?

### ISSUE THREAD

**Issue by phsumi** [rgommezz/react-native-offline#154]
Hi all

I landed here because of the limitations in `NetInfo` and this looks like a really well maintained package - kudos! Now, I'm using MobX, and would prefer to have some sort of a background service that monitors connectivity (similar to `NetInfo`s events), and then take it from there myself. So basically, I'm looking for an API that can tell me when my connection changed, rather than a component.

Is this feasible with this library and where it's going, or am I better off writing my own?

Thanks!

Context: Basically, I'd end up with smth like this that would provide me with observable states:

```
export class ConnectivityStore {
    @observable isConnected: boolean = false;
    @observable isWifi: boolean = false;

    //interna that monitor/react on connectivity changes
}
```

**Comment by rgommezz** [comment]
Hi @phsumi,

Unfortunately there are no plans at the moment to support `Mobx`, so you'd have to roll your own solution. 

However, if something reusable comes out of it, I'd be happy to accept an external PR to add support.

I think you'd have to use `Rx.Observable.fromEvent(NetInfo.isConnected, 'connectionChange')` to turn the connection change event into an observable.

Also, if you wanna detect the initial connection, you can leverage [checkInternetConnection](https://github.com/rgommezz/react-native-offline#checkinternetconnection) from this library.

Good luck!

**Comment by phsumi** [comment]
I'll have a look - thanks!

**Comment by jayeshanandani** [comment]
@phsumi any luck using this with mobx?
