### ISSUE TITLE
NetworkConsumer unreliable in simulator

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rgommezz/react-native-offline#164]
I'm only at the development stage so have only got as far as running on an ios simulator, but I'm finding that the NetworkConsumer is unreliable if I turn my mac's wifi off & on - seems to work when first turning the wifi off, but then it normally doesn't pick up a change when turning it back on (though it did once or twice). Should I be worried? Is it reliable in production?

**Comment by rgommezz** [comment]
Hey @JeremyBradshaw7, you shouldn't be worried. That's something that I've experienced quite often while using iOS simulators. They are quite buggy in that sense and unfortunately there is nothing we can do at the moment to prevent that.

On real devices you won't see that issue happening.

**Comment by JeremyBradshaw7** [comment]
Thanks @rgommezz
