### ISSUE TITLE
Upgrade Redux Saga to 1.x

### ISSUE THREAD

**Issue by jeveloper** [rgommezz/react-native-offline#165]
I would really like to see your dependency updated to the next stable 1.x 

thank you @rgommezz  

hope you can push that to npm soon, even as a beta tag

**Comment by pekq** [comment]
I tried to force the resolution with https://github.com/rogeriochaves/npm-force-resolutions without luck. Are there any other workarounds?

**Comment by nmchr7** [comment]
Hi 👋 I just ran into this issue today, so I've forked this lib and made it use redux saga v1. I haven't tested it much yet, but seems to be working fine so far 😅 Here's the [link](https://www.npmjs.com/package/@nmchr7/react-native-offline) if you want to try i out.

Hope it helps 😄

**Comment by iyucef** [comment]
any update about this issue ?

**Comment by iyucef** [comment]
Is there any update about this issue?

**Comment by rgommezz** [comment]
New version release that fixes it, `v4.3.1`
