### ISSUE TITLE
Not detecting when connection regained

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rgommezz/react-native-offline#166]
react-native-offline is working nicely for detecting when a connection is lost (almost immediately), but not so good at detecting when a lost connection is regained. This has been reported by customers. Can reproduce in-house when ipad is on wi-fi by turning airplane mode off & back on again - is this a realistic test? Is this a known issue? Should this work irrespective of whether connection is via wi-fi or 3G?

I'm using NetworkProvider / NetworkConsumer with defaults. With pingInterval not specified (default 0), how long is it expected to take to detect a regained connection?

Because my NetworkProvider is at root level, the only thing that seems to detect whether the app is online again is to remove the app from memory and restart.

**Comment by rgommezz** [comment]
Hey @JeremyBradshaw7,

This sounds to me like a problem with the core `NetInfo` package itself, since I am just setting the listeners they offer for connectivity changes and building utilities & components with a nice API on top of.

I'd suggest you open a issue (and optionally link it to this one) to either React Native core or the new dedicated lean package https://github.com/react-native-community/react-native-netinfo.

**Comment by kneza23** [comment]
It is the same problem with me. On iOS i just can't detect when device is online back again. On Android everything works fine.

**Comment by RockyRx** [comment]
@kneza23 Not working on Android as well. When disconnect and reconnect to 4G/3G it's not regaining connectivity.

**Comment by grit96** [comment]
Did anyone solve this issue? I'm having the same problem here.

**Comment by JeremyBradshaw7** [comment]
I'm now setting the pingInterval to 20s so at least it detects when back online within 20s:

`      <NetworkProvider pingInterval={20000}>`

I'm cautious about setting a lower value because I don't want it pinging continually.

**Comment by LeviYoder2112** [comment]
I've been having the same issue intermittently. `isConnected` always changes quickly when I disable wifi/data on my iPhone, but it doesn't always update when wifi/data is re-enabled. I'm using `<ReduxNetworkProvider>` .
One way I've been able to work around this is to call the `checkInternetConnection()`function included with the library. After calling the function, I'm dispatching the CONNECTION_CHANGE action type to update the network reducer's `isConnected` state.

Example: 
```
import {
  checkInternetConnection,
  offlineActionTypes,
} from 'react-native-offline';

export const internetChecker = () => {
  async function thunk(dispatch) {
    const isConnected = await checkInternetConnection();
    dispatch({
      type: offlineActionTypes.CONNECTION_CHANGE,
      payload: isConnected,
    });
  }
  return thunk;
};
```

**Comment by haikyuu** [comment]
Thanks @JeremyBradshaw7 setting a ping interval fixes the problem.
