### ISSUE TITLE
Java Error on using a custom url for checkInternetConnection

### ISSUE THREAD

**Issue by tconn89** [rgommezz/react-native-offline#170]
React Native offline package version: ''3.11.1"

I'm getting this error - `java.lang.String cannot be cast to java.lang.Double`

```javascript
// Causes error
const isConnected = await checkInternetConnection('https://google.com');
// This works fine
const isConnected = await checkInternetConnection(10000, 'https://google.com');
```

This should be mentioned in the docs that the parameter ordering has been changed for `checkInternetConnection`

**Comment by rgommezz** [comment]
This is properly reflected in the [old docs](https://github.com/rgommezz/react-native-offline/blob/master/docs_3x.md#checkinternetconnection)
