### ISSUE TITLE
Is it possible to delay offline queue flush

### ISSUE THREAD

**Issue by nicemanis** [rgommezz/react-native-offline#174]
Hey, I was wondering if it is possible to control how the actionQueue is flushed after regaining connectivity.

Currently, it will automatically flush the queue as soon as connectivity is regained. However, I would like to manually trigger the queue flush. Otherwise, if the app is closed and reopened later when there is a network connection, I need to perform some initialization before the queue is flushed.

**Comment by rgommezz** [comment]
Hello @nicemanis,

Unfortunately there is no way at the moment to do that. Happy to discuss a potential implementation so that you can build a PR for that feature.

**Comment by MakhouT** [comment]
I think this is a duplicate of https://github.com/rgommezz/react-native-offline/issues/160
Notice that @emanueleDiVizio has created a [PR](https://github.com/rgommezz/react-native-offline/pull/225) for this. 
@rgommezz Would be good if you could take a look at this.
