### ISSUE TITLE
how to edit items in the actionQueue

### ISSUE THREAD

**Issue by hariDasu** [rgommezz/react-native-offline#176]
my application requirements dictate that the user must be able to edit items while they are in the queue. i would be able to match the item  in the queue (via a `filter()`) but i am not sure if there is any method to update the item. I do not think my reducer would have access to the `actionQueue[]` contained in my state tree. any ideas?

**Comment by hariDasu** [comment]
I ended up making my own queue from a redux-saga actionChannel, and attaching `offlineItems()` as an object in my state tree,  to permit editing via reducers. i am still using this lib, but just for the convenience methods of network connectivity polling and the context renderers.

**Comment by rgommezz** [comment]
Hey @hariDasu,

Unfortunately that's not supported at the moment since the queue is immutable. Happy you could tailor your own solution and make it work with this library.
