### ISSUE TITLE
Document online assumption

### ISSUE THREAD

**Issue by scarlac** [rgommezz/react-native-offline#177]
**What happened?**
Library fails to notify of online status despite doing an online check.

**What was expected?**
Library does it's online check AND notifies/triggers handler.

**Solution Proposal**
We should document that react-native-offline assumes that application is online by default. When an application starts up, if they are already online, no event will trigger. While this may seem like fair behavior, it's not necessarily obvious to a user of the library. If an application restores its entire redux state and keeps track of connection status, an application may restore itself into 'offline mode' when it starts up, but react-native-offline will not tell you otherwise. This is due to the optimization of `prevState.isConnected !== isConnected` code that only triggers handlers if online status changes, not what it initially is (assumed online).

- We document that the library assumes that you are online and ONLY triggers a notification if you go offline, OR...
- Trigger handler initially when app starts up with connection change that lets users know if they are currently on- or offline (since library is already doing the check). Potentially this initial call can be opted out of

**Comment by rgommezz** [comment]
That use case is already [documented](https://github.com/rgommezz/react-native-offline#how-to-orchestrate-redux-to-dispatch-connection_change-as-the-first-action-when-the-app-starts-up).

If you'd like to rephrase the FAQ section for easier finding I am opened to a PR :)
