### ISSUE TITLE
ReduxNetworkProvider with react-native-navigation - could not find store

### ISSUE THREAD

**Issue by dpellier** [rgommezz/react-native-offline#184]
Hi,

I'm trying to use the v4.x.x with [react-native-navigation](https://github.com/wix/react-native-navigation) and can't make the new `ReduxNetworkProvider` work.

Here is a simple example of what I'm trying to do
```
import { applyMiddleware, combineReducers, createStore } from 'redux';
import { Provider } from 'react-redux';
import { reducer as networkReducer } from 'react-native-offline';

const rootReducer = combineReducers({
    network: networkReducer
});
const store = createStore(rootReducer, applyMiddleware(thunk, logger));

// Registering the screen as described here https://wix.github.io/react-native-navigation/#/docs/top-level-api-migration?id=registering-screens-with-wrapping-provider-component
Navigation.registerComponent('Home', () => (props) => (
        <Provider store={ store }>
            <Home {...props} />
        </Provider>
    ), () => Home);
```

In my Home component, I can access the network `isConnected` value, though it is always true.
So I've tried to add the `ReduxNetworkProvider` with a `pingInterval` to check the connectivity.
```
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import { ReduxNetworkProvider } from 'react-native-offline';
import { connect } from 'react-redux';

class Home extends Component {
    render() {
        return (
            <ReduxNetworkProvider pingInterval={3000}>
                <Text>You're { this.props.isOnline ? 'online' : 'offline' }</Text>
            </ReduxNetworkProvider>
        );
    }
}

function mapStateToProps({ network }) {
    return {
        isOnline: network.isConnected
    }
}
export default connect(mapStateToProps)(Home);
```

But then I get the following error:
<img width="361" alt="Screenshot 2019-04-16 at 11 18 59" src="https://user-images.githubusercontent.com/1390934/56197921-1fd60480-603a-11e9-9d5a-7edd4ac06310.png">

It looks like the `ReduxNetworkProvider` is not a descendant of the react-redux <Provider> component.
Am I using it the wrong way?

Lib used:
```
"react": "16.8.3",
"react-native": "0.59.4",
"react-native-navigation": "2.17.0",
"react-native-offline": "4.3.1",
"react-redux": "7.0.2",
"redux": "4.0.1",
"redux-logger": "3.0.6",
"redux-thunk": "2.3.0"
```

**Comment by rgommezz** [comment]
Hello,

Have you followed the [react-native-navigation](https://wix.github.io/react-native-navigation/#/docs/third-party?id=registercomponentwithreduxscreenid-generator-provider-store) instructions to integrate redux?

**Comment by dpellier** [comment]
Yes, I did.
`Navigation.registerComponentWithRedux` from your link is deprecated, they now advise to do it like:
```
// Registering the screen as described here https://wix.github.io/react-native-navigation/#/docs/top-level-api-migration?id=registering-screens-with-wrapping-provider-component
Navigation.registerComponent('Home', () => (props) => (
        <Provider store={ store }>
            <Home {...props} />
        </Provider>
    ), () => Home);
``

**Comment by weisssean** [comment]
Same issue here, using react-native-offline. I even removed the navigation and just called a simple component and it still doesn't work:


    export default class App extends Component 
    {
        render() {
            return (
                <Provider store={store}>
                    <ReduxNetworkProvider>
                        <LoginView />
                    </ReduxNetworkProvider>
                </Provider>
            );
        }
    }


`
"dependencies": {
    "@turf/turf": "^5.1.6",
    "expo": "^31.0.4",
    "moment": "^2.22.2",
    "native-base": "^2.8.1",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
    "react-native-action-button": "^2.8.5",
    "react-native-dialog-input": "^1.0.5",
    "react-native-offline": "^4.3.1",
    "react-native-paper": "^2.1.3",
    "react-native-picker-select": "^5.0.0",
    "react-native-super-grid": "^2.4.3",
    "react-navigation": "^2.18.2",
    "react-navigation-material-bottom-tabs": "^0.4.0",
    "react-navigation-redux-helpers": "^2.0.8",
    "react-redux": "^6.0.0",
    "redux": "^4.0.0",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-thunk": "^2.3.0"
  }
`

**Comment by stereu** [comment]
Same here using react-navigation.

**Comment by Serginh0** [comment]
Alguma solução?

**Comment by mslavik2** [comment]
I got it to work in my project by making sure I only had 1 version of react-redux installed. Make sure the version this package depends on resolves to the same one your code uses. (react-redux@^6.0.0 currently)

**Comment by YoshiYo** [comment]
Hi,

I searched a solution to use the react-redux ^7.1.0 in my app and to use this package too.

According to the changelog of react-redux, the ^7.1.0 seems be ok for the this package. I looked the code for the ReduxProvider and I didn't see any requirements to not use ^7.1.0. Someone can confirm ?
I don't know if the other components provided by this package need the ^6.0.0 of react-redux, but for redux, it works on my side.

So to do the tricks with yarn, I used the [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) method. 
Add in your package.json :
```
"resolutions": {
    "react-redux": "^7.1.0"
  },
```
Then execute and try it in your app. 
`rm -rf nodes_modules`
`yarn install`

**Comment by nikhilgoswami** [comment]
I could not get it to work even after using react-redux@6.0.0

**Comment by philyboysmith** [comment]
Reverting to ^6.0 worked for me.

**Comment by nikhilgoswami** [comment]
I switched to using sagas

**Comment by jsina** [comment]
actually I remove the react-redux dependency form my package.json file and it's worked for me

**Comment by creative-git** [comment]
SAME PROBLEM

**Comment by umbrella-kirill-karpov** [comment]
@rgommezz, could you take a look at this PR https://github.com/rgommezz/react-native-offline/pull/201 and apply if it suits you. This PR resolves the issue.

**Comment by rgommezz** [comment]
Latest version 4.3.2 should resolve the issue, please give it a try

**Comment by hutsi** [comment]
upgrading react-redux from 6.0.1 to 7.2.0 works for me!
