### ISSUE TITLE
Option to pass headers to pingServerUrl

### ISSUE THREAD

**Issue by liran90** [rgommezz/react-native-offline#186]
if you use custom pingServerUrl which is behind an API gateway for instance (which requires api key) you would want an option to pass custom headers

**Comment by rgommezz** [comment]
Hey @liran90, happy to accept a PR to support that :)

**Comment by emanueleDiVizio** [comment]
We're having the same issue @rgommezz, might open a PR for this if planning allows :+1:

**Comment by emanueleDiVizio** [comment]
Good news, I've opened a PR for this! @rgommezz -> https://github.com/rgommezz/react-native-offline/pull/228
