### ISSUE TITLE
Queueable thunks with Typescript

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rgommezz/react-native-offline#187]
> For thunks, append interceptInOffline and meta properties to the function returned by the action creator, where meta has the same shape as for Flux actions.

As far as I know, Typescript does not support adding arbitrary properties to functions. Any idea how this can be supported in Typescript?

```
actions.ts:536:6 - error TS2339: Property 'interceptInOffline' does not exist on type '(dispatch: any, getState: any) => Promise<void>'.

536   fn.interceptInOffline = true;
         ~~~~~~~~~~~~~~~~~~
```

**Comment by rgommezz** [comment]
Hey @JeremyBradshaw7, this is a TS issue that is not related to the library itself. I am not much of an expert on TS matters, hopefully you've found the solution to your problem elsewhere.

**Comment by JeremyBradshaw7** [comment]
I haven't, since I parked this work, but perhaps someone else from the community could suggest a solution.

**Comment by kosbog** [comment]
@JeremyBradshaw7 
```
export type ThunkAction<
  R, // Return type of the thunk function
  S, // state type used by getState
  E, // any "extra argument" injected into the thunk
  A extends Action // known types of actions that can be dispatched
  > = (dispatch: ThunkDispatch<S, E, A>, getState: () => S, extraArgument: E) => R;

export type AppThunk<ReturnType = void> = ThunkAction<
  ReturnType,
  RootState,
  unknown,
  AnyAction
>;

// Extend with all what you need 
//
export interface ExtendAppThunk extends AppThunk {
  interceptInOffline?: boolean;
  meta?: { [key: string]: boolean | string | string[] };
}
```
