### ISSUE TITLE
isConnected prop not updating on iOS

### ISSUE THREAD

**Issue by DannyDAtRivall** [rgommezz/react-native-offline#190]
Android works fine, but using <NetworkProvider> and <NetworkConsumer> on iOS can correctly detect when a connection is lost, but not regained. 

I know that this is redundant of other posts, and that it was "fixed" on January 1st, but the issue is still there with "react-native": "0.59.5", "react-native-offline": "^4.3.1", and iOS 12.1 as well as 12.3.  We've tried setting NSAllowArbitraryLoads (as referenced here: https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http/40299837#40299837) and several other solutions all on a physical device.

**Comment by ngvazquezbdsol** [comment]
@DannyDAtRivall 
Hi, have the similar problems. Whats do you solutions?

**Comment by DannyDAtRivall** [comment]
None, just had to move on
