### ISSUE TITLE
Action is not getting added in queue for Redux-Saga

### ISSUE THREAD

**Issue by tayyabaAslam** [rgommezz/react-native-offline#193]
Hi, I am setting my action like this:

```
export const getData = (headers) => ({
  type: 'GET_DATA',
  payload: headers,
	meta: {
		retry: true
	}
})
```

And for saga I set 
```
yield all([
    fork(networkSaga, { pingInterval: 200, pingInBackground: true }),
    yield takeLatest(Types.GET_DATA, getData, api)
])
```

but when I call the action in offline mode, it does not add it in queue.

Note: I am getting updated value for isConnected. Just queue is not adding actions.

Is anything missing?

**Comment by lewatt23** [comment]
Same issue here

**Comment by rgommezz** [comment]
It seems that you forgot to set up the [middleware](https://github.com/rgommezz/react-native-offline#createnetworkmiddleware) for the redux store. You can follow [this example](https://github.com/rgommezz/react-native-offline/blob/master/example/redux/createStore.js#L14) as a reference
