### ISSUE TITLE
Is connected is always true - network sagas

### ISSUE THREAD

**Issue by lewatt23** [rgommezz/react-native-offline#194]
Hello guys thanks for the lib is all i have been looking for!,but i have a problem since i setup the lib with redux sagas using the doc i aways get isConnected to be true even when i don't have connection.

Here is my config

//rootsagas

import { networkSaga } from 'react-native-offline';

// all  sagas  are  found here
```
export default function* rootSaga () {

  yield all([
    fork(AddQuestion),
    fork(GetQuestion),
    fork(GetReply),
    fork(AddReply),
    fork(Login),
    fork(Page),
    fork(Register),
    fork(watcherGetnotes),
    fork(watcherUpdatePassword),
    fork(watcherUpdateUsername),
    fork(watcherUpdatePhoto),
    fork(Notification),
    fork(networkSaga, { pingInterval: 200, pingInBackground: true }),
 
```
```

//store setup

import { applyMiddleware, compose, createStore} from 'redux';
import  rootSaga   from "./Rootsaga";
import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage' // defaults to localStorage for web and AsyncStorage for react-native

import createSagaMiddleware from "redux-saga";
import rootReducer from './rootReducer'; //Import the root reducer
import {
  withNetworkConnectivity,
  reducer as network,
  createNetworkMiddleware
} from "react-native-offline";

// create the saga middleware
const sagaMiddleware = createSagaMiddleware();
const networkMiddleware = createNetworkMiddleware({
  queueReleaseThrottle: 200,
});

//redux persist
const persistConfig = {
  key: 'root',
  storage,
  blacklist: ["isNetworkBannerVisible"] 
}
const persistedReducer = persistReducer(persistConfig, rootReducer)


export  const store = createStore(persistedReducer,compose(applyMiddleware(networkMiddleware, sagaMiddleware)));
export  const persistor = persistStore(store);
  

// run the saga
sagaMiddleware.run(rootSaga);


```

**Comment by Ligia-Andreica** [comment]
I had a similar issue due to conflicting redux-saga versions in the project dependencies (`v1.0.2` and `v0.16.2`). You can use `yarn list` to check the installed dependencies.

To fix it, define the custom version inside your dependencies through the `resolutions` field in `package.json`.

**Comment by lewatt23** [comment]
Hello @Ligia-Andreica thanks for your reply, yes in my package.json I have` v0.16.2` and when type yarn list I see the same v1.0.2 as you. please, can you explain your fix? I don't understand what you mean should I upgrade to v1.0.2?. Thanks for your reply...

**Comment by Ligia-Andreica** [comment]
There is no need to upgrade. You can set the version of redux-saga by adding `resolutions` in `package.json`. The following will remove the conflict, keeping just `v0.16.2`.

```  
"resolutions": {
    "redux-saga": "0.16.2"
}
```

It's what the readme explains in more details [here](https://github.com/rgommezz/react-native-offline#using-redux-saga-100-betax), except the library has been upgraded to use `v1.0.2` and I assume your project is using `v0.16.2` (like mine).

**Comment by lewatt23** [comment]
@Ligia-Andreica  thanks for your help, but adding resolutions in my case did not do the job, what I instead did was to upgrade to v1.0.3 and everything works!. Thanks
