### ISSUE TITLE
Is this library incompatible with thunks and redux persist?

### ISSUE THREAD

**Issue by d3vhound** [rgommezz/react-native-offline#203]
I'm trying to dispatch the same thunk more than once with different payloads and only 1 gets saved to the actionQueue, my code is the same as the README.md, how would you accomplish multiple thunks that are the same but with different arguements?

Thanks

**Comment by bneigher** [comment]
@d3vhound I ended up using the actions that this library dispatches and made my own action queueing system due to this problem.

Do note the flag you can try for getting multiple actions with the same type: https://github.com/rgommezz/react-native-offline/pull/185

**Comment by rgommezz** [comment]
Hey @d3vhound, that should be fixed on version `5.1.0`.

Here is the [documentation in the matter](https://github.com/rgommezz/react-native-offline#managing-duplicate-actions)
