### ISSUE TITLE
[Question] Confirm and update installation steps on iOS with autolinking

### ISSUE THREAD

**Issue by rszalski** [rgommezz/react-native-offline#205]
Hello!

When installing this package via `yarn add react-native-offline` (without having previously installed the `@react-native-community/netinfo`) I can confirm that `@react-native-community/netinfo` gets installed as a dep but `pod install` inside the `/ios` dir _does not_ pick the pods for `@react-native-community/netinfo` this results in a broken installation, without native modules installed on iOS.

What I had to do to fix this, was to first install `@react-native-community/netinfo`, run `pod install` (it was correctly picked up this time) and then install `react-native-offline` on top of that.

I'm not sure if this is a problem with `autolinking` where it doesn't pick up such nested dependancies or some kind of problem with my RN setup. I'd love for someone to confirm this behavior. If it's a problem, we can simply update the docs to mention the order above.

I don't believe this would happen for normal `react-native link` as that would have been explicit.

Thank you for all the hard work on this module!

**Comment by rgommezz** [comment]
Hey @rszalski!

Thank you for reporting this.

I am not sure whether it's an existing issue with autolinking or not, but I'd bet it does not pick nested dependencies. As a defensive measure, we could update the docs. Would you like to create a quick PR for that? :)

Otherwise, I'll try to do it myself in some days.

**Comment by rszalski** [comment]
@rgommezz I added a PR for this: https://github.com/rgommezz/react-native-offline/pull/218 Let me know if it sounds good.
