### ISSUE TITLE
Option to pass in a custom comparison function to detect similar thunks in queue

### ISSUE THREAD

**Issue by LiquidSean** [rgommezz/react-native-offline#206]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/rgommezz/react-native-offline/issues/206)

I am curious on thoughts of having a custom comparison function for thunks being added to queue. To elaborate further I would like to have more control over actions being added to the queue. What could help is being able to define a comparison function for actions that will be added to the queue. So when these actions are added a comparison function would be run to determine if a match exists. If a match exists replace current queued action with new one. This comparison is on the thunks actual parameters so IDs or other parameters. This would ensure uniqueness for items added. Thoughts on this would be appreciated.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#208 Feat: Option to pass in custom comparison function](https://issuehunt.io/r/rgommezz/react-native-offline/pull/208)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/rgommezz/react-native-offline/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by rgommezz** [comment]
Hey @LiquidSean, that sounds like a good idea! We could have the default `isEqual` comparison function to be run, unless a custom one is provided otherwise. We could have a new config prop for the [middleware factory](https://github.com/rgommezz/react-native-offline#createnetworkmiddleware), something like `queueComparisonFn`.

Happy to accept a PR for that :)

**Comment by LiquidSean** [comment]
Here is what I am thinking for passing in a comparison Fn. Would this make sense? So you would assign the comparison Fn at the time you would assign `interceptOffline` property.

```
export const fetchUser = (url) => {
  function thunk(dispatch) {
    fetch(url)
      .then((response) => response.json())
      .then((responseJson) => {
        dispatch({type: FETCH_USER_SUCCESS, payload: responseJson});
      })
      .catch((error) => {
        console.error(error);
      });
  };

  thunk.interceptInOffline = true;
  thunk.queueComparisonFn = someFn;
  return thunk; // Return it afterwards
};
```

**Comment by rgommezz** [comment]
I'd prefer having a generic comparison function that applies to all the actions in the queue. You'd have then the flexibility to determine when 2 actions are the same, both plain objects and thunks. Basically providing your own [getSimilarActionsInQueue](https://github.com/rgommezz/react-native-offline/blob/8a56ad80631056483b27fc9d41f2eae1da2a1816/src/utils/getSimilarActionInQueue.js)

```js
export default function createReduxStore() {
  const networkMiddleware = createNetworkMiddleware({
    comparisonFn: (action, queue) => { ... // do your comparision }
  });

  const sagaMiddleware = createSagaMiddleware();

  const rootReducer = combineReducers({
    foo,
    bar,
  });

  const middlewares = [networkMiddleware];

  const store = createStore(rootReducer, applyMiddleware(...middlewares));
}
```

**Comment by LiquidSean** [comment]
@rgommezz would you recommend passing the comparison function into the reducer? So in `handleOfflineAction` this check for which comparison function will be done.

```js
    const similarActionQueued = comparisonFn
      ? comparisonFn(actionWithMetaData, state.actionQueue)
      : getSimilarActionInQueue(actionWithMetaData, state.actionQueue);

```

**Comment by rgommezz** [comment]
Yes, that sounds good!

Let's create a factory function and export it as the new API for the `networkReducer`.

```js
// configureStore.js
import { createStore, combineReducers } from 'redux'
import { createReducer as createNetworkReducer } from 'react-native-offline';

const rootReducer = combineReducers({
  // ... your other reducers here ...
  network: createNetworkReducer(comparisonFn),
});

const store = createStore(rootReducer);
export default store;
```

Then inside the reducer we'll pass that function along to the handler:

```js
const createReducer = (comparisonFn = getSimilarActionInQueue) =>
 (state: NetworkState = initialState, action: *) => {
  switch (action.type) {
    case actionTypes.CONNECTION_CHANGE:
      return {
        ...state,
        isConnected: action.payload,
      };
    case actionTypes.FETCH_OFFLINE_MODE:
      return handleOfflineAction(state, action, comparisonFn);
    case actionTypes.REMOVE_FROM_ACTION_QUEUE:
      return handleRemoveActionFromQueue(state, action.payload);
    case actionTypes.DISMISS_ACTIONS_FROM_QUEUE:
      return handleDismissActionsFromQueue(state, action.payload);
    default:
      return state;
  }
}
```

What do you think?

**Comment by LiquidSean** [comment]
@rgommezz I like that idea. I will try and start working on this.

**Comment by kodeGenius** [comment]
Is this issue still open?

**Comment by nerdomancer** [comment]
When are you guys planning to merge #208 to fix this issue?

**Comment by rgommezz** [comment]
@all-contributors please add @LiquidSean for code and doc

**Comment by rgommezz** [comment]
Closed by https://github.com/rgommezz/react-native-offline/pull/208

**Comment by Relentl3zz** [comment]
If I understood right, its only possible to delete 1 item off the action Queue, would it be possible to allow an array of actions to remove.

For Example in Action Queue: 

SAVE_TODO_ITEM
DELETE_TODO_ITEM

You could of course leave it in the action Queue and there will be no bugs, but I would prefer to not send it to the backend at all.

For now I can only find one Action and delete it from the Queue, I tried to return an array but that doesnt work either.

Is it currently possible to delete multiple items, or is there another feature for it?
