### ISSUE TITLE
Could not find store in the context of "Connect(ReduxNetworkProvider)".

### ISSUE THREAD

**Issue by Chandrakala-B** [rgommezz/react-native-offline#207]
I always get this error.
![Simulator Screen Shot - iPhone X - 2019-08-16 at 09 01 25](https://user-images.githubusercontent.com/46925824/63147443-d57e8780-c01b-11e9-8a0b-807a61f12a04.png)

My App.js file
render() {
return (
<AppContainer
ref={navigatorRef => {
NavigationService.setTopLevelNavigator(navigatorRef);
}}>
);
}

Could you please help me on this to resolve.

**Comment by LiquidSean** [comment]
@Chandrakala-B you need to wrap your App in a provider.

```js
<Provider store={store}>
    <App /> 
</Provider>

```

**Comment by rgommezz** [comment]
Closing due to being stale.

**Comment by horodnicdragos** [comment]
I have the same behvariour when using a switch navigator wrapped in a Provider. I don't think this issue should be disregarded that easily. I'm using `react-redux 7.1.1` and `react-native offline 5.1.0`.

**Comment by helderburato** [comment]
I upgrade from `react-redux 7.1.0` to `react-redux 7.1.3` and it's worked.

**Comment by okeybond** [comment]
i upgraded to 7.1.3, no luck - also using SwitchNavigator

**Comment by dickerpulli** [comment]
@okeybond @horodnicdragos Did you solve the problem? I still got this problem. 
@rgommezz Could you reopen the issue because it is not solved in every case.

**Comment by ankeetmaini** [comment]
Can you provide a repro repo/snack?

**Comment by dickerpulli** [comment]
I currently have another problem: 
If i add the ReduxNetworkProvider into my component tree the app crashed/ends immediately after startup.

I have a git repo here https://github.com/dickerpulli/react-native-expo-demo
and also a running snack here https://snack.expo.io/@dickerpulli/b47cc9

If you remove the ReduxNetworkProvider inside the App.js render() function everything works fine.

**Comment by ankeetmaini** [comment]
@dickerpulli this is because `NetInfo` is included inside `ReduxNetworkProvider` component. This seems to be `NetInfo` issue, since your repro uses Expo, I found 
these issues related to NetInfo which other people are having not related to this module.

https://github.com/react-native-community/react-native-netinfo/issues/297
https://github.com/react-native-community/react-native-netinfo/issues/289

Could you see if this helps?

**Comment by dickerpulli** [comment]
Thank you. I currently fixed my issue with using react-native-offline 5.2.0 instead of the latest one.
