### ISSUE TITLE
(question) best practice for changing pingInterval

### ISSUE THREAD

**Issue by seankwalker** [rgommezz/react-native-offline#209]
Hi! 👋 first of all to the maintainers, thanks so much for the incredible library--it's outstanding!

I wondered if there's a best practice to changing the `pingInterval` of the `ReduxNetworkProvider`. I'd like to send pings more frequently when the app is disconnected from internet, to ideally update connection status sooner.

Thanks!

**Comment by rgommezz** [comment]
Hello @seankwalker, thanks for your kind words! 🤗 

I think your best shot is to keep the `pingIntervalTime` on your redux state and change it with an action. Then, you could have a wrapper connected component on your entry point, that sits on top of `ReduxNetworkProvider`. Something along these lines:

```js

import store from './reduxStore';
import React from 'react';
import { Provider, connect } from 'react-redux';
import { ReduxNetworkProvider } from 'react-native-offline';

let App = () => (
  <Navigator>
    <MainScreen />
    <OtherScreen />
  </Navigator>
);

const Wrapper = ({ pingTime }) => <ReduxNetworkProvider pingInterval={pingTime} />

const ConnectedReduxNetworkProvider = 
	connect(state => ({ pingTime: state.config.pingTime }))(Wrapper)

const Root = () => (
  <Provider store={store}>
    <ConnectedReduxNetworkProvider>
      <App />
    </ConnectedReduxNetworkProvider>
  </Provider>
);
```

Lemme know if that works.

**Comment by rgommezz** [comment]
Hey @seankwalker, good catch!

I forgot to add the necessary `children` prop to the `Wrapper`. 

I've updated my previous comment to reflect that.

**Comment by rgommezz** [comment]
I am planning to rewrite the library with hooks at some point, which would make super easy to implement that scenario, as well as opening up the door for incorporating features more flexibly.

Having said that, I am still open for a PR, so feel free to submit one :)
