### ISSUE TITLE
(question) I can't get it to work

### ISSUE THREAD

**Issue by yasir-netlinks** [rgommezz/react-native-offline#214]
I am sorry for posting this here, but I am not sure how to make this work for me
I added the `createNetworkMiddleware`
```
const networkMiddleware = createNetworkMiddleware({
  queueReleaseThrottle: 200
});
//
const store = createStore(
    persistedReducer,
    applyMiddleware(networkMiddleware, sagaMiddleware, thunk)
  );
```
in my `Actions`
```
export const getUserFollowedComp = (limit, offset, searchTerm) => {
  async function thunk(dispatch, getState) {
    const { _id } = getState().loginInfoReducer.decoded_token;
    const token = getState().loginInfoReducer.raw_token;

    dispatch(fetchUserFollowedComp());

    let url = `/user/${_id}/followedCompanies`;
    let queryFilter = {
      limit: limit,
      skip: offset,
      searchTerm: searchTerm
    };
    try {
      const res = await instance.get(
        `${url}?filter=${JSON.stringify(queryFilter)}`,
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      );
      const data = res.data;
      dispatch(fetchUserFollowedCompSuccess(data))
    } catch (err) {
      let error = error_parser(err);
      dispatch(fetchUserFollowedCompFailure(error));
    }
  }
  thunk.interceptInOffline = true;
  thunk.meta = {
    retry: true
  };
  return thunk;
};
```
Also, I added `network` to reducers
```
import { reducer as network } from "react-native-offline";
const allReducers = combineReducers({
    ...
    network
})
```
### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | ^5.0.0
| react-native         |  0.59.10
| node                 |  v12.4.0
| npm or yarn          |  6.9.0

**Comment by rgommezz** [comment]
Have you wrapped your app with a `ReduxNetworkProvider`?

**Comment by yasir-netlinks** [comment]
@rgommezz no I haven't done that, just to be clear, is this what im missing out
```
import React from 'react';
import { NetworkProvider } from 'react-native-offline';
import App from './App';

const Root = () => (
  <NetworkProvider>
    <App />
  </NetworkProvider>
);

export default Root;
```

**Comment by rgommezz** [comment]
Probably, please take a look at [the documentation](https://github.com/rgommezz/react-native-offline#usage-2) to integrate the `network` reducer into redux, specially the step 2.

`createNetworkMiddleware` seems to be correctly configured as per your snippet.

**Comment by yasir-netlinks** [comment]
@rgommezz hi , so I managed to get it to work, thanx. Before closing this issue, I wanted some clarifications, first of, what is this for exactly `queueReleaseThrottle: 200`. and second, please correct me if I understood wrong, when queuing offline, it intercepts in offline-mode and send action `@@network-connectivity/FETCH_OFFLINE_MODE` , and I can use this `if(action.type === offlineActionTypes.FETCH_OFFLINE_MODE)` in my reducer to optimistically inform the user that their action will be processed once they are online (e.g. submitting a form), keeping in my I have to have `transforms` in order to persist and rehydrate that particular action. I hope thats about it!

**Comment by rgommezz** [comment]
1. [queueReleaseThrottle](https://github.com/rgommezz/react-native-offline#po-config)

2. That's correct, but make sure your actions are [queueable as well](@@network-connectivity/FETCH_OFFLINE_MODE) by using the `meta` property

**Comment by yasir-netlinks** [comment]
Hi @rgommezz sorry for this again but wanted to regarding this statement
```
When you attempt to fetch data on the internet by means of dispatching a plain action or a thunk in offline mode, the middleware blocks the action and dispatches an action of type @@network-connectivity/FETCH_OFFLINE_MODE instead,
```
when it blocks the action, does that mean the execution of the thunk function will stop there, or will it continue ?? e.g.


```
// the app is offline
export const getUserFollowedComp = (limit, offset, searchTerm) => {
  async function thunk(dispatch, getState) {
    //
    dispatch(fetchUserFollowedComp());       // <== does it still continue executing ?
    //
   try  {
   //
   dispatch(fetchUserFollowedCompSuccess(data)) // <== does it still continue executing ?
    } catch (err) {
      dispatch(fetchUserFollowedCompFailure(error)); // <== or this too ?
    }
  }
  thunk.interceptInOffline = true;
  thunk.meta = {
    retry: true
  };
  return thunk;
};
```

**Comment by yasir-netlinks** [comment]
@rgommezz  Ok , it seems that on app start, my page loads right after the store is being rehydrated (redux).. and the function runs and misses being intercepted 
```
componentDidMount(){
     this.props.getData();     // it keeps executing even though offline
}
```
I found this after adding a `setTimout`
```
componentDidMount(){
     setTimeout(() => {
           this.props.getData();   // now its intercepted and execution is blocked
     }, 3000)
}
```
Any ideas ?

**Comment by horodnicdragos** [comment]
In my case it seems to never dispatch FETCH_OFFLINE_MODE nor block the action no matter how much I delay it.
