### ISSUE TITLE
Forcing to offline mode in case of spotty connectivity, after a certain number of pings

### ISSUE THREAD

**Issue by amolventurit** [rgommezz/react-native-offline#217]
If there is low internet speed then how to flipping to offline.

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline |4.1.0
| react-native         |0.59.2
| node                 |v10.15.0
| npm or yarn          |1.16.0

**Comment by rgommezz** [comment]
Just dispatch the below action to force the application into offline mode:

```js
import { offlineActionTypes } from 'react-native-offline';

{
  type: offlineActionTypes.CONNECTION_CHANGE,
  payload: false,
}
```
