### ISSUE TITLE
NetworkConsumer 

### ISSUE THREAD

**Issue by gr8guyramesh** [rgommezz/react-native-offline#221]
### Current Behavior

Its working fine with network  Connection with online and offline  except one scenario, like while connect with hotspot. 
•	Connect with Hotspot and switch off mobile data then its showing Connected as true.

### Expected Behavior
If connected to hotspot with  switch off mobile data then its showing 
"Connected as true , need to show Coonected as false

### How to reproduce

-<NetworkConsumer>
      {({ isConnected }) => (
        isConnected ? (
          <Button title="Download image" onPress={downloadImage} />
        ) : (
          <Text>Downloading images is disabled since you are offline</Text>
        )
      )}
    </NetworkConsumer>

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | '5.0.0'
| react-native         | '0.60.5
| node                 | 10.14.2
| npm or yarn          | 6.4.1

**Comment by rgommezz** [comment]
Hi @gr8guyramesh,

This library does not implement any native code to detect internet connection, just uses the existing `NetInfo` module. As per your description, it could be a bug when that particular scenario happens.

Please do open an issue on their [repository](https://github.com/react-native-community/react-native-netinfo).

Good luck!

**Comment by gr8guyramesh** [comment]
Okay, sure I will open an Issue on their repository. thanks
