### ISSUE TITLE
How to access netinfo connection type?

### ISSUE THREAD

**Issue by rdgomt** [rgommezz/react-native-offline#224]
Hi! Thanks for the library.

I wonder if there is a way to access information about the connection type (wifi, 4g, etc).

**Comment by rgommezz** [comment]
Not at the moment, but it would be nice to enhance the information we get from `NetInfo`. I know they offer methods to get such information, besides connectivity. 

PR more than welcome :)

**Comment by Tyak99** [comment]
Hello, @rgommezz Can I pick up this task?

**Comment by rgommezz** [comment]
Sure @Tyak99! More than welcome. Let me know if you need more help or context

**Comment by Tyak99** [comment]
Hello @rgommezz. Thank you for this opportunity. I started working on the task and I have a question.
* Should I make the `netinfo connection type` available in the `NetworkConsumer` i.e something like this
```
<NetworkConsumer>
      {({ isConnected, type }) => (
        isConnected ? (
          <Text> You are conneced to a ${type} network</Text>
        ) : (
          <Text>You are offline</Text>
        )
      )}
</NetworkConsumer>
```
And other places where `isConnected` is being returned from:
1. Network reducer
2. checkInternetConnection();

Or should I just write an on-demand utility like `checkInternetConnection()` that returns the network type?

**Comment by Tyak99** [comment]
Hi @rgommezz. Happy new year. I want to bring your attention to the question I asked above 👆So I would know how to proceed on the task. Thank you

**Comment by rgommezz** [comment]
Hey @Tyak99, same to you!

This library uses https://github.com/react-native-community/react-native-netinfo#netinfostate behind the scenes, so we just need to dump all the remaining state from `NetInfoState` (besides `isConnected`) into the `network` reducer. You'll have to modify `NetworkConnectivity.tsx`, `saga.ts`, `createReducer.ts` and `actionCreators.ts` to make that happen.

**Comment by grit96** [comment]
@rgommezz I've thrown together a draft PR implementing this https://github.com/rgommezz/react-native-offline/pull/342

I will polish it and test it in a real app tomorrow.

**Comment by tylercaceres** [comment]
getting netInfo's `isConnected` would also be nice - especially if we could toggle what we want this library's 'isConnected' to reflect -- if we dont want to ping every X amount of seconds.
