### ISSUE TITLE
WiFi reconnection not recognized when App is inactive

### ISSUE THREAD

**Issue by knight-hub** [rgommezz/react-native-offline#231]
## Environment
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 550.87 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Platforms
The issue only happens on iOS, everything works as expected on Android.

## Versions

- Android: N/A
- iOS: 13.1.2
- react-native-netinfo: 4.6.0
- react-native: 0.61.2
- react: 16.9.0

## Description
Im using the following code to display a message when the user is offline:
```js
<NetworkProvider>
    <NetworkConsumer>
               {({ isConnected }) =>
                        isConnected ? null : (
                            <View style={pageStyles.container}>
                                <Text style={pageStyles.text}>{t('app.offline')}</Text>
                            </View>
                        )
                }
    </NetworkConsumer>
</NetworkProvider>
```
When I turn of WiFi the mesage shows as expected. Also the message disappears as expected if I turn WiFi back on provided the App is open while the connection is created. However should the control center be open while the WiFi connection changes from disconnected to connected, (e.g. open control center, enable WiFi, wait for connection, close control center) then the message stating the user is offline will not disappear. The same thing happens, if I disable WiFi while in the App, then let the App go to the background, enable WiFi again and wait for it to connect. Getting the App back out from the background later, it still shows the offline message and the message also doesn't go away with time.

I also found the following odd behaviour: When I am online and have an offline message that does not disappear on screen 1 and I navigate to another screen (screen 2) that would also render an offline message if I would be offline, this screen does not show an offline message (as it should be). Navigating back to screen 1 I will see the offline message again (not as it should be) even though screen 2 obviously realized that the user is online.

Also I'm testing on a real iOS device not on a Simulator.

## Expected behavior
The offline message should only show when the user actually is offline.

**Comment by rgommezz** [comment]
Hello @knight-hub, thanks for the detailed report.

Have you tried enabling the [following props](https://github.com/rgommezz/react-native-offline#networkprovider), `pingOnlyIfOffline` and `pingInBackground` on the `NetworkProvider`?

**Comment by knight-hub** [comment]
Thank you very much for the quick reply @rgommezz, I tried enabling the two suggested props and found setting `pingInBackground={true}` really solved the problem and the offline Message is now functioning as expected.

On the other hand I'm wondering if this change makes the app ping google.com continuously even while its not active, which would probably drain the battery faster than necessary. I would rather have the App only ping when it changes from inactive to active, the way I believe it worked on Android with `pingInBackground={false}`. 

Is there a way to get my offline message to work on iOS without pinging continuously even when the app is in the background?

As everything works with default props in Android and setting `pingInBackground={true}` in iOS feels like a workaround, I think this is a bug and wonder if you would fix it?

**Comment by ankeetmaini** [comment]
You can use `pingInterval` to control the frequency of ping.
