### ISSUE TITLE
CONNECTION_CHANGE as the first action

### ISSUE THREAD

**Issue by LeviYoder2112** [rgommezz/react-native-offline#235]
### Current Behavior

I'm using the code provided in the FAQ, pertaining to dispatching `CONNECTION_CHANGE` as the first action upon app startup.
It works well, if the `CONNECTION_CHANGE` action is changing `isConnected` form `false` to `true`.
However, if isConnected was `true` when the app shut off, and I dispatch `CONNECTION_CHANGE` upon startup, the queue is not flushed, because `isConnected` isn't actually changing.

The reason I have actions in the queue, despite `isConnected` being `true`, is that I'm also intercepting and queueing requests that don't receive a response in xxxx milliseconds, as touched on in the FAQ.
Any recommendations on using the `CONNECTION_CHANGE` action on app startup to flush the queue even if `isConnected` isn't actually changing from `false` to `true`?

**CODE FROM FAQ REGARDING CONNECTION_CHANGE DISPATCH ON APP STARTUP**
```
// configureStore.js
import { createStore, applyMiddleware } from 'redux';
import { persistStore } from 'redux-persist';
import AsyncStorage from '@react-native-community/async-storage';
import { createNetworkMiddleware, offlineActionCreators, checkInternetConnection } from 'react-native-offline';
import rootReducer from '../reducers';

const networkMiddleware = createNetworkMiddleware();

export default function configureStore(callback) {
  const store = createStore(rootReducer, applyMiddleware(networkMiddleware));
  const { connectionChange } = offlineActionCreators;
  // https://github.com/rt2zz/redux-persist#persiststorestore-config-callback
  persistStore(store, { storage: AsyncStorage }, () => {
    // After rehydration completes, we detect initial connection
    checkInternetConnection().then(isConnected => {
      store.dispatch(connectionChange(isConnected));
      callback(); // Notify our root component we are good to go, so that we can render our app
    });
  });

  return store;
}
```

```
// App.js
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import configureStore from './store';
import Root from './Root';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isLoading: true,
      store: configureStore(() => this.setState({ isLoading: false })),
    };
  }

  render() {
   if (this.state.isLoading) return null;

    return (
      <Provider store={this.state.store}>
        <Root />
      </Provider>
    );
  }
}

export default App;
```

### Expected Behavior

I'm expecting my dispatch of `CONNECTION_CHANGE` upon app startup to flush the queue if `isConnected` is `true`, regardless of whether it was true or false before dispatching `CONNECTION_CHANGE`.

### How to reproduce
I'm currently using axios instead of fetch, so that I can implement the axios timeOut method and queue my request if it times out. Timed-out requests are being queued as I intended:

```
//action that calls request
export const axiosPost = (inputData) => {
  async function thunk(dispatch) {
    const axios = require('axios').default;
    let source = axios.CancelToken.source();
    setTimeout(() => {
      source.cancel('timeout');
    }, 1); // set timeout to 1 ms, to ensure that fetchOfflineMode is called and thunk is queued
    return axios
      .post(url, inputData, {cancelToken: source.token})
      .then(result => {
        console.log(result);
        stateClone.sent = true;
        dispatch({type: DATA_SENT, payload: inputData});
      })
      .catch(function(thrown) {
        if (axios.isCancel(thrown)) { // if timeout is triggered
          console.log('Request canceled', thrown.message);
          dispatch(fetchOfflineMode(thunk));
        } else {
          console.log(inputData, url);
          alert(thrown);
        }
      });
  }
  thunk.interceptInOffline = true;
  thunk.meta = {
    retry: true,
    name: 'axiosPost',
    args: {uuid: stateClone.uuid, data: inputData, eeCode: eeCode},
  };
  return thunk;
};
```

Great library! Everything has been working very well for me, I'm just curious about how to flush the queue upon dispatch of `CONNECTION_CHANGE` at app startup, even if isConnected isn't actually changing from `false` to `true`

**Comment by rgommezz** [comment]
Hey @LeviYoder2112, I think we could create and export a new action to consumers to explicitly flush the queue if desired, no matter the network connection.

Would you like to work on a PR for that? Should be straightforward :)
