### ISSUE TITLE
Unable to resolve module after updating to 5.2.0

### ISSUE THREAD

**Issue by yasir-netlinks** [rgommezz/react-native-offline#238]
I am getting the error below after updating from `5.0.0` to `5.2.0`

![Screen Shot 2019-12-30 at 14 28 05](https://user-images.githubusercontent.com/26054956/71577227-f77f2f00-2b10-11ea-9344-abf381faf492.png)

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline |  ^5.2.0
| react-native         |   0.61.5
| node                 |    v12.4.0
| npm          |   6.9.0

**Comment by LawEKS** [comment]
In the same boat...

Were you able to resolve this issue yourself?

**Comment by LawEKS** [comment]
I was having a similer issue with react-native-svg and found this: https://github.com/react-native-community/react-native-svg/issues/1165#issuecomment-546101731

> I had the same issue, with same steps and same outcome. Figured out that in my app.json i had
> `"packagerOpts": { "config": "metro.config.js", "sourceExts": ["js","jsx","svg",] },`
> insead of
> `"packagerOpts": { "config": "metro.config.js", "sourceExts": [ "js","jsx","svg","ts","tsx"] },`
> changing that fixed my issue
