### ISSUE TITLE
Error : RNCNetinfo.getCurrentState got 2 arrguments expected 3

### ISSUE THREAD

**Issue by zuntilZ** [rgommezz/react-native-offline#239]
when update react-native-community/netinfo 4.6 to 5.2  , I am   using **ReduxNetworkProvider**  and the error below after . I think  to verrsion ^5.2.0 errrors . 

![Untitled](https://user-images.githubusercontent.com/7069320/71640516-1ff85c00-2cbe-11ea-8747-90d422bfe93b.png)

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | 5.2.0
| react-native         | 0.61.5
| @react-native-community/netinfo | ^5.2.0

**Comment by nikhilgoswami** [comment]
@zuntilZ  How did you resolve this?

**Comment by zuntilZ** [comment]
> @zuntilZ How did you resolve this?

you back redux version 4.0.4 .
