### ISSUE TITLE
Slow connection detection

### ISSUE THREAD

**Issue by jacky-ew** [rgommezz/react-native-offline#243]
### Current Behavior
Sometimes app gets isConnected as `false` when connection is slow

### Expected Behavior
its expected but what is the standard / threshold triggering the state change

### How to reproduce
scenario:
1. going into a life with internet connection
2. connection got weak in the lift / unstable

May i know when or how will the state change if the connection is weak? is there any way to configure it?

**Comment by rgommezz** [comment]
Hey @jacky-ew,

I think our option would be to leverage [this configuration](https://github.com/react-native-community/react-native-netinfo#configure). We'd have to enhance the library by being able to provide those parameters - this library uses react-native-community/react-native-netinfo behind the scenes

**Comment by Joshmatjjen** [comment]
@rgommezz How can the ping Timeout be used in the <NetworkConsume  isConnected >
