### ISSUE TITLE
Update NetInfo to 5.5.0

### ISSUE THREAD

**Issue by grit96** [rgommezz/react-native-offline#253]
NetInfo have recently added web support in https://github.com/react-native-community/react-native-netinfo/pull/292.

Currently it is not possible for me to use the latest version of NetInfo due to the use of rollup in `react-native-offline`, so please can you bump NetInfo to 5.5.0 which added web support?

**Comment by ankeetmaini** [comment]
@rgommezz should this be upgraded? Or should we switch to not bundling it like [bob](https://github.com/react-native-community/bob) or integrate it for our build? This will just output different files which the users can then import by specifying extensions at their end for different targets.

**Comment by rgommezz** [comment]
Please try the latest version `5.6.0`

I've updated the documentation and relaxed the dependencies, to make it compatible with both RN >= 60 and Expo SDK >=35.

You can install any version of [react-native-community/react-native-netinfo](https://github.com/react-native-community/react-native-netinfo), as long as it's  between the range >=4.6 && <6.0
