### ISSUE TITLE
add support react-redux v7.2.0

### ISSUE THREAD

**Issue by magickasoft** [rgommezz/react-native-offline#254]
### How to reproduce

updated package `react-redux` to v7.2.0

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | 5.4.0
| react-native         | 0.61.5
| node                 | v12.16.0
| npm or yarn          | 6.13.4 / 1.22.0

**Comment by rgommezz** [comment]
Please use the latest version `5.6.0`. `react-redux` is not a direct dependency anymore, but rather a peer dependency, so you can install any version higher than `7.x`
