### ISSUE TITLE
Could not find "store" in the context of "Connect(ReduxNetworkProvider)"

### ISSUE THREAD

**Issue by magickasoft** [rgommezz/react-native-offline#260]
library does not work with updated packages
"react-redux": "^7.2.0"

| software             | version
| ----------------     | -------
| react-native-offline | 5.4.0
| react-native         | 0.61.5
| node                 | v12.16.1
| npm or yarn          | 1.22.0

**Comment by Gueoff** [comment]
this lib installs react-redux and redux libs. You may have theses modules in double in your yarn/package.lock.
You must "yarn remove redux react-redux react-native-offline" then "yarn add react-native-offline" to make it works and have only one version of redux

**Comment by rgommezz** [comment]
To fix it add the below in your package.json.

```
  "resolutions": {
    "react-native-offline/react-redux": "7.1.0" // This should match the one in your package.json
  }
```
