### ISSUE TITLE
Basic Jest test will not work

### ISSUE THREAD

**Issue by thegregthomp** [rgommezz/react-native-offline#271]
### Current Behavior

I'm setting up a boilerplate for a new RN app and just trying to get a basic Jest test in and I can not get it to work with 'react-native-offline' no matter what I try. See image below for error.

Getting error: Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules

### Expected Behavior

Tests should work

### How to reproduce

Setup a basic RN app, install this package and run a test

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | 5.6.1
| react-native         | 0.62.2
| node                 | 10.16
| npm or yarn          | 1.13

### App-test.js
 
```
import 'react-native';
import React from 'react';
import App from '../app/entrypoint';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

test('renders correctly', () => {
  const tree = renderer.create(<App />).toJSON();
  expect(tree).toMatchSnapshot();
});
```

### jest.config.js
```
module.exports = {
  verbose: true,
  "transformIgnorePatterns": [
    "node_modules/(?!(react-native|async-storage|react-native-offline|react-redux|invariant|react-native-offline|@react-native-community)/)",
  ],
  "transform": {
    "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
  },
  setupFiles: [
    "./node_modules/react-native-gesture-handler/jestSetup.js"
  ],
  "globals": {"__DEV__": true}
};
```

### babel.config.js

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};

```

![image](https://user-images.githubusercontent.com/1554124/82268382-d8a4fc00-993c-11ea-9fe8-860997db51ea.png)

**Comment by thegregthomp** [comment]
This test was running via `jest.config.js`. When I move it back to `package.json` I get a similar but different error: 

![image](https://user-images.githubusercontent.com/1554124/82271567-1bb79d00-9946-11ea-95b2-0fd61d022e32.png)

This leads me to believe it's something with netinfo. I went all through netinfo, did their fix for mocking and STILL the same error.

**Comment by chuenlum** [comment]
I get the same issue as mentioned in https://github.com/rgommezz/react-native-offline/issues/271#issuecomment-630504704.

The same error message was seen: `@react-native-community/netinfo: NativeModule.RNCNetInfo is null`, and it occurs on the same line: `import { reducer as networkReducer } from 'react-native-offline';`

Some packages that might be relevant to this:

- react-native-offline 5.4.0
- @react-native-community/netinfo 5.9.0, also 5.7.0
- redux-saga 1.1.3

I don't have a solution even when implementing mocks for @react-native-community/netinfo via these methods:

- https://github.com/react-native-community/react-native-netinfo#errors-while-running-jest-tests
- https://github.com/react-native-community/react-native-netinfo/issues/219#issuecomment-537422975
- https://github.com/react-native-community/react-native-netinfo/issues/75#issuecomment-488277512

Might it be that the root cause is within react-native-offline package?

**Comment by rgommezz** [comment]
Hi folks,

The error seems to indicate you are not mocking properly the `NetInfo` native module this library uses behind the scenes.

I spotted something odd in your `jest.config.js` file:

```js
setupFiles: [
   "./node_modules/react-native-gesture-handler/jestSetup.js"
],
```

That should reference your own setup file, where you should mock all modules with native dependencies.

```js
setupFiles: ['<rootDir>/jest.setup.js']
```

The code you need to add there to mock `NetInfo` is:

```js
import mockRNCNetInfo from '@react-native-community/netinfo/jest/netinfo-mock.js';

jest.mock('@react-native-community/netinfo', () => mockRNCNetInfo);
```

Have you tried that?

**Comment by chuenlum** [comment]
Yes I have tried that. I've followed netinfo's readme example to place it in the rootdir, I've also tried placing it in __mocks__/@react-native-community directory, with and without adding in package.json jest key. All of these turned up the same error.

**Comment by thegregthomp** [comment]
@rgommezz Same, here's a look at my jest.setup.js:

`import RNCNetInfoMock from '@react-native-community/netinfo/jest/netinfo-mock.js';

jest.mock('@react-native-community/netinfo', () => RNCNetInfoMock);

import mockAsyncStorage from '@react-native-community/async-storage/jest/async-storage-mock';

jest.mock('@react-native-community/async-storage', () => mockAsyncStorage);`

**Comment by MPiccinato** [comment]
Just wanted to voice that I am experiencing the same issue as @thegregthomp and @chuenlum. With the same lines in my jest setup.

**Comment by hamaron** [comment]
I faced the same problem and made it work by the following code in my `setup.js` file:

```
import { NativeModules } from 'react-native';

NativeModules.RNCNetInfo = {
  getCurrentState: jest.fn(() => Promise.resolve()),
  addListener: jest.fn(),
  removeListeners: jest.fn()
};
```
