### ISSUE TITLE
Can not send custom headers with ReduxNetworkProvider

### ISSUE THREAD

**Issue by ugurakkurt** [rgommezz/react-native-offline#274]
**Current Behavior** 

I am using ReduxNetworkProvider to detect internet connection of client and I use our backend api endpoint for pinging. However, I can not send any custom headers when sending ping request.

**Expected Behavior**

Normally, I manually set some device info in headers in other api endpoints and save them within session in backend. However as I cannot send them via ReduxNetworkProvider, this causes session data inconsistencies in our system. Would it be possible to send any custom header(other than session data which is automatically handled by react native) via ReduxNetworkProvider props maybe?

**How to reproduce**

```
<ReduxNetworkProvider
        pingServerUrl={url}
        pingInBackground={false}
        pingTimeout={5000}
        shouldPing={true}
        pingInterval={20000}
      >
        <PersistGate loading={null} persistor={persistor}>
          <PaperProvider>
            <App />
          </PaperProvider>
        </PersistGate>
      </ReduxNetworkProvider>
```

**Your Environment**

react-native-offline | 5.6.1
react-native | 0.62.2

**Comment by ugurakkurt** [comment]
I realized there was a PR to fix this --> https://github.com/rgommezz/react-native-offline/pull/228
May I ask why this wasn't merged? @rgommezz

**Comment by rgommezz** [comment]
Hey @ugurakkurt,

Sorry, there was a complete refactor of the library to TS in between and that PR got obsolete.

If you have the time to replicate the same changes in a separate PR I am happy to include it

**Comment by ugurakkurt** [comment]
Here it is --> https://github.com/rgommezz/react-native-offline/pull/275 @rgommezz

**Comment by ugurakkurt** [comment]
@rgommezz Would you review the PR?

**Comment by rgommezz** [comment]
Done @ugurakkurt :)
