### ISSUE TITLE
How to use this library for RN<60 ?

### ISSUE THREAD

**Issue by sauravjmt** [rgommezz/react-native-offline#279]
### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. 
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline |
| react-native         |
| node                 |
| npm or yarn          |

**Comment by rgommezz** [comment]
Hello,

Unfortunately this library is not compatible with versions of RN lower than 0.60.

Sorry for any inconvenience.
