### ISSUE TITLE
Split README in a better package documentation

### ISSUE THREAD

**Issue by helderburato** [rgommezz/react-native-offline#288]
## Description

In the last months I've used a lot the package and it's amazing, thanks @rgommezz!

I was thinking about how to improve the docs and break the sections in a more readable way, I saw a lot of projects using the following documentation tools:
- [Docsify](https://docsify.js.org/#/);
- [Docusaurus](https://docusaurus.io/);

What do you think about the move from just `README` to one of them? I can help with this.

**Comment by rgommezz** [comment]
Hey @helderburato, that sounds awesome! 😀

I am happy to go with whichever tool you prefer.

Looking forward to seeing that boost in the docs 🚀

**Comment by caiangums** [comment]
Let me know if you need any help! 😄

**Comment by helderburato** [comment]
> Hey @helderburato, that sounds awesome! 😀
> 
> I am happy to go with whichever tool you prefer.
> 
> Looking forward to seeing that boost in the docs 🚀

Amazing! I'll give a check to some tools and share them with you.

@caiangums do you wanna check some of these tools and test it?

**Comment by helderburato** [comment]
I and @caiangums searched about `Docusaurus` and `Docsify` and we chose the [Docusaurus](https://docusaurus.io/) to improve the docs. @rgommezz  What do you think about it?

**Comment by rgommezz** [comment]
Fantastic, let's go with Docusaurus! 🦖
