### ISSUE TITLE
Finish web support started in #253

### ISSUE THREAD

**Issue by colmbrady** [rgommezz/react-native-offline#291]
### Current Behavior

-  NPM module 5.7.0 is not usable with react-native-web V13.

### Expected Behavior

- This library can support web since react-native-community/react-native-netinfo#292.

### How to reproduce

- Rollup packages native verison of netinfo, therefore this cant work on Web.

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | 5.7.0 (latest)
| react-native         | (63+)
| node                 | (10 LTS)
| npm or yarn          | (yarn latest)

**Comment by colmbrady** [comment]
https://github.com/rgommezz/react-native-offline/pull/290

**Comment by rgommezz** [comment]
@all-contributors please add @colmbrady for code
