### ISSUE TITLE
Questioning about Test for 'action ENQUEUED, status back ONLINE'

### ISSUE THREAD

**Issue by CrushyChilli** [rgommezz/react-native-offline#297]
I have been looking a testing example for 'action ENQUEUED, status back ONLINE'.

But the example seems that it is not what I am looking for,
I am using saga for API request, but It did not fire the saga function after it back to online,
even I did add the action into the queue as initial state.

` store.dispatch(connectionChange(true));`<-- It does not re-dispatch any enqueued offline action.

Is there any way to test if the action inside the offline get re-dispatch after the connection changed into ONLINE?

**Comment by rgommezz** [comment]
Hey @CrushyChilli,

It's difficult to answer your question without some code examples.

The re-dispatch & flushing the queue occurs when there is a transition from `isConnected` from `false` to `true`. If you dispatch it manually and the `state` was already indication network connectivity nothing will happen.
