### ISSUE TITLE
Error coming from redux-saga, when using ReduxNetworkProvider

### ISSUE THREAD

**Issue by mattvaldez** [rgommezz/react-native-offline#299]
I am using the library following the instructions for [Integration with Redux](https://github.com/rgommezz/react-native-offline#integration-with-redux). I am using ReduxNetworkProvider, and have followed the documentation provided. I am not using networkSaga, and I am not using redux-saga at all in my app. However, my users are experiencing issues in production, and the error I am logging is coming from redux-saga. This library is the only library in the app that has redux-saga as a dependency. I am having a incredibly hard time troubleshooting this issue. Any advice is appreciated. Below is the stacktrace for the error. Thank you.

`TypeError undefined is not an object (evaluating 'a.length') 
    node_modules/redux-saga/dist/redux-saga-core-npm-proxy.cjs.js:20:18 
    node_modules/redux-saga/dist/redux-saga-core-npm-proxy.cjs.js:20:18 createTaskIterator
    node_modules/redux-saga/dist/redux-saga-core-npm-proxy.cjs.js:20:18 
    node_modules/@babel/runtime/helpers/nonIterableSpread.js:2:22 exports
    node_modules/@babel/runtime/helpers/nonIterableSpread.js:2:22 setValue
    node_modules/@babel/runtime/helpers/nonIterableSpread.js:2:22 _nonIterableSpread
    node_modules/redux-saga/dist/redux-saga-core-npm-proxy.cjs.js:20:18 w
    node_modules/redux-logger/dist/redux-logger.js:1:460 
    node_modules/@babel/runtime/helpers/nonIterableSpread.js:2:22 exports
    node_modules/@babel/runtime/helpers/nonIterableSpread.js:2:22 
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:6 _callTimer
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 _callImmediatesPass
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:11 callImmediates
    [native code] callImmediates
    node_modules/react-native/Libraries/Components/AccessibilityInfo/NativeAccessibilityManager.js:59:46 exports
    node_modules/react-native/Libraries/Components/AccessibilityInfo/NativeAccessibilityManager.js:59:46 
    node_modules/react-native/Libraries/Components/AccessibilityInfo/NativeAccessibilityManager.js:59:46 exports
    node_modules/react-native/Libraries/Components/AccessibilityInfo/NativeAccessibilityManager.js:59:46 getConstants
    [native code] value
    [native code] value`

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | 5.6.1
| react-native         | 0.61.1
| node                 | 13.12.0
| npm or yarn          | 1.22.4

**Comment by rgommezz** [comment]
Hey @mattvaldez, 

Sorry for the late reply, unfortunately I don't have much time to actively keep an eye on this library any more.

`redux-saga` is a [peer dependency](https://github.com/rgommezz/react-native-offline/blob/master/package.json#L110)

Could you try to install some `1.0.x` version explicitly?

`yarn add redux-saga@1.0.0`
