### ISSUE TITLE
Not working properly on continues internet connection change.

### ISSUE THREAD

**Issue by sankar9659** [rgommezz/react-native-offline#300]
I'm using this package for detect the network connection,
My issue is, if i open the app with network connection on state (network enabled in mobile), It shows as network connected,
Then if i disconnect the network, it shows network disconnected, Then again if i connect the internet, its still shows network disconnected. Any one faced this issue with this scenaio, And i'm using redux toolkit, some time it working with some delay,
It takes upto 1 min.
My code is,

**App.js** 
`import React, { useEffect } from 'react';`
`import { NetworkProvider } from 'react-native-offline';`
`import { Provider } from 'react-redux';`
`import { SafeAreaProvider } from 'react-native-safe-area-context';`

`const App = () => {
  useEffect(() => {
    SplashScreen.hide();
  }, []);`

  `return (`
     ` <Provider store={store}>`
        `<NetworkProvider`
         ` pingTimeout={1000}`
          `pingServerUrl='https://www.google.com/'`
          `shouldPing={true}`
          `pingOnlyIfOffline={false}`
          `pingInBackground={true}`
        `>`
          `<Router />`
        `</NetworkProvider>`
      `</Provider>`
  )
}`

`export default function NavigationApp() {
  return <SafeAreaProvider><App /></SafeAreaProvider>
};`

Index.js file:
	`<NetworkConsumer>
						{({ isConnected }) => (
							isConnected ? (
								<Text>Connected</Text>
							) : (
									<Text>Internet not connected</Text>
								)
						)}
					</NetworkConsumer>`
					
"react": "17.0.1",
"react-native": "0.63.3",
 "react-native-offline": "^5.7.0",
 Please reply for this issue.

**Comment by sankar9659** [comment]
Its working in real device, but i have tested in emulator. Issue fixed
Thanks.

**Comment by sebadiaz-arg** [comment]
I've same issue in emulator. Also when I change the network connection between Wifi and Data mobile into emulator. It don't work properly there.
