### ISSUE TITLE
Expo: on the web not working.

### ISSUE THREAD

**Issue by sergeu90** [rgommezz/react-native-offline#316]
### Current Behavior
When i use in the web i get error 
![image](https://user-images.githubusercontent.com/7217517/117777740-92c7fe80-b245-11eb-924f-2511bf4bbf0a.png)

<NetworkProvider>

### Expected Behavior
On the ios and android it is work but on the web not working.

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | 5.8.0
| react-native         | sdk-40.0.1
| node                 |  14.16.1
| npm or yarn          | 6.14.12

**Comment by colmbrady** [comment]
#291 They dont maintain this repo anymore :(

**Comment by poptocrack** [comment]
Any update on this @rgommezz ?

**Comment by rgommezz** [comment]
Hey guys, sorry fo the delay!

I've shipped version 6.0.0 that includes web support
