### ISSUE TITLE
Saga side effect not being called after an action is auto dispatched from the `actionQueue` (When network state changes from offline to online)

### ISSUE THREAD

**Issue by kusalshrestha** [rgommezz/react-native-offline#325]
### Current Behavior
The saga side effect is not invoked. However the action from the actionQueue is dispatched.
In my case:
1. When online
- dispatch `FETCH_CUSTOMERS` - OK
- dispatch `FETCH_CUSTOMERS_SUCCESS` after api call - OK

2. When network state changes from offline to online
- dispatch `FETCH_CUSTOMERS` - OK
- But it's side effect does not call. (i.e no api call happens)

<img width="1071" alt="Screen Shot 2021-07-08 at 11 12 04 AM" src="https://user-images.githubusercontent.com/10921013/124868095-fc168480-dfde-11eb-99e5-c2d56e23ebc7.png">

<img width="1065" alt="Screen Shot 2021-07-08 at 11 28 55 AM" src="https://user-images.githubusercontent.com/10921013/124868599-b4dcc380-dfdf-11eb-9e93-1ba29442507b.png">

actions.js
```
...
import { createAction } from 'redux-actions'

export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const fetchCustomers = createAction(FETCH_CUSTOMERS, (payload = {}) => payload, () => ({ retry: true }))
````

saga.js
```
import { all, call, fork, put, take } from 'redux-saga/effects'

import * as actions from './actions'
import * as api from '../../services/api'

 function* workfetchCustomers() {
  try {
    const data = yield call(api.fetchCustomers) // network api call
    yield put(actions.fetchCustomersSuccess(data))
  } catch (err) {
    yield put(actions.fetchCustomersFailure(err))
  }
}

function* watchfetchCustomers() {
  while (true) {
    yield take(actions.FETCH_CUSTOMERS)
    yield call(workfetchCustomers)
  }
}

export default function* rootSaga() {
  yield all([fork(watchfetchCustomers), fork(watchFetchProfile)])
}

```

middleware
```
  const networkMiddleware = createNetworkMiddleware({
    regexActionType: /^FETCH/,
    actionTypes: ['FETCH_CUSTOMERS'],
    queueReleaseThrottle: 1000,
  })
```

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | ^5.8.0
| react-native         | 0.64.2
| redux-saga          | 1.1.3
| node                 | 16.4.1
| npm or yarn          | 1.22.10

**Comment by pankaj9singh** [comment]
same issue, can we reopen this please?

**Comment by daybreaker** [comment]
Did you ever solve this?

I am having the same issue, using redux-saga v1.1.1

my action is dispatched from the actionQueue, and the reducer sets `saving: true` like it should. But the saga itself is never called.

edit: If anyone is having this issue, double check that you're following the correct order when doing `applyMiddleware(networkMiddleware, sagaMiddleware)`  as mentioned in [the Usage section](https://github.com/rgommezz/react-native-offline#usage-4)  🤦🏻‍♂️
