### ISSUE TITLE
Problems with the connection in some devices

### ISSUE THREAD

**Issue by shardaishwak** [rgommezz/react-native-offline#341]
### Current Behavior

- What code are you running and what is happening?
I am using the hook for listening to connection changes, but sometimes, on client devices, the connection is given as offline, even though the user is active. I tried changing the host for ping and interval, but the problem persists. The problem persists only on some devices (iOS in particular)
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/45267574/139879700-bcf70fcf-90ef-45c9-9e6d-f953a9dd3fef.png)
The red bar indicates that the isConnected variable is false, on Wi-Fi and mobile data, even though the user has a connection. 

### Expected Behavior

- What do you expect should be happening?
The package should register the connection changes without a problem

### How to reproduce

- You must provide a way to reproduce the problem. 
I can't provide the source code as it is a private project but can share the main code that is used
![image](https://user-images.githubusercontent.com/45267574/139880199-661e2480-43c9-417a-8d28-e6dcf192217b.png)
Here is where all the Provider is initialized, the root of the whole app.
![image](https://user-images.githubusercontent.com/45267574/139880323-910479ed-b420-4733-b885-4f627d2cdbfe.png)
This is how it is being imported into a component.
![image](https://user-images.githubusercontent.com/45267574/139881511-6276abe3-b783-4d4a-9489-6003de34ba72.png)
Here I am using the variable to show the message indicated in the screenshot.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | ^6.0.0
| react-native         | 0.64.2
| node                 | 14.18.1
| npm or yarn          |  yarn = 1.22.4 - npm = 8.1.1

NOTE: The problem persists only on some devices of our clients.

**Comment by shardaishwak** [comment]
@react-native-community/netinfo has fixed the issue with the latest release @6.2.1. Can be update it in this package?

**Comment by Engazan** [comment]
Same problém On Samsung phones, it happens when app is in background for 10 min and then reopen it appers offline
