### ISSUE TITLE
Feature request: configurable namespace for meta 

### ISSUE THREAD

**Issue by mikesol** [rgommezz/react-native-offline#53]
As per a brief exchange with @rauliyohmc on https://github.com/rauliyohmc/react-native-offline/pull/49, I would like to open an issue to discuss modifying how `react-native-offline` writes to the `meta` namespace.  In my use case, I have had to rename a metadata key in my production code from `dismiss` to something else because the `meta` namespace is hardcoded in the project.  This was found after a fair bit of debugging thinking there was a bug with `react-native-offline` when in fact it was just a namespace collision.

What would be great is to be able to programatically change the namespace (for example, `action.meta.foo.bar` instead of `action.meta`) so that projects can avoid namespace collisions.

**Comment by rgommezz** [comment]
Stale issue, closing.
