### ISSUE TITLE
Manually trigger connectivityCheck

### ISSUE THREAD

**Issue by DCKT** [rgommezz/react-native-offline#63]
Hello,

I didn't found a way to manually trigger a connectivityCheck in the code, is there a way to do this ?

Thanks.

**Comment by rauliyohmc** [comment]
Hello,

It's not supported at the moment. However, that should be an easy PR, since it's just exposing https://github.com/rauliyohmc/react-native-offline/blob/master/src/checkInternetAccess.js as part of the public API :)

**Comment by DCKT** [comment]
Fine I will do a PR ASAP 😉

Le 21 déc. 2017 19:05, "Raúl Gómez Acuña" <notifications@github.com<mailto:notifications@github.com>> a écrit :

Hello,

It's not supported at the moment. However, that should be an easy PR, since it's just exposing https://github.com/rauliyohmc/react-native-offline/blob/master/src/checkInternetAccess.js as part of the public API :)

**Comment by rgommezz** [comment]
Closed with #99
