### ISSUE TITLE
pingServerUrl does not work for servers that do not support HEAD 

### ISSUE THREAD

**Issue by macrozone** [rgommezz/react-native-offline#74]
if you use a server that does not support HEAD (i tried with https://spaces.archilogic.com), it always reports offline.

These servers report a 405 error on the HEAD command.

you can test that with curl -i --head https://spaces.archilogic.com

**Comment by rgommezz** [comment]
Could you make a PR to make that configurable? :)

**Comment by tscharke** [comment]
I created this [PR](https://github.com/rgommezz/react-native-offline/pull/122) to support custom http methods for method **withNetworkConnectivity**, only. Http-methods _HEAD_ and _OPTIONS_ only.
