### ISSUE TITLE
Configuration for behaviour when app is backgrounded

### ISSUE THREAD

**Issue by jesperlndk** [rgommezz/react-native-offline#76]
I see that the pinging keeps running even if the app is backgrounded.

What do you think about adding an option for configuring this behaviour? It might not always be good that the pinging continues endlessly when the app is background.

PS. Great job on making this library, @rauliyohmc! Thanks a lot.

**Comment by rgommezz** [comment]
Hey @jesperlndk,

That sounds great, we could discuss here how the API could look like :)

Let me know what you have in mind in terms of implementation

**Comment by repapa** [comment]
I agree @jesperlndk, @rgommezz hoping for your implementation on this and I would like to say thank you for creating this wonderful library.

**Comment by rgommezz** [comment]
Solved with https://github.com/rgommezz/react-native-offline/pull/97 :)

Closing this.
