### ISSUE TITLE
[QUESTION] How to re-dispatch thunk actions when user goes back online?

### ISSUE THREAD

**Issue by johhansantana** [rgommezz/react-native-offline#81]
I have done some troubleshooting on getting this to work with redux and redux-thunk.

I haven't got to the redux-persist part yet because I want to figure out a few things before that.

For example, I had to redo the `configureStore.js` configuration to dispatch the `isConnected` boolean each time the connection changes.

```javascript
import { Platform, NetInfo } from "react-native";
import { createStore, applyMiddleware, compose } from "redux";
import thunk from "redux-thunk";
import {
  createNetworkMiddleware,
  offlineActionTypes
} from "react-native-offline";
import rootReducer from "../src/reducers";

const networkMiddleware = createNetworkMiddleware();

// on iOS, the listener is fired immediately after registration
// on Android, we need to use `isConnected.fetch`, that returns a promise which resolves with a boolean
function isNetworkConnected(store) {
  if (Platform.OS === "ios") {
    return new Promise(resolve => {
      const handleFirstConnectivityChangeIOS = isConnected => {
        // changes the redux state of isConnected
        store.dispatch({
          type: offlineActionTypes.CONNECTION_CHANGE,
          payload: isConnected
        });
        resolve(isConnected);
      };
      // add event listener to listen to connection changes
      NetInfo.isConnected.addEventListener(
        "connectionChange",
        handleFirstConnectivityChangeIOS
      );
    });
  }

  return NetInfo.isConnected.fetch();
}

export default function configureStore(callback) {
  const store = createStore(
    rootReducer,
    compose(applyMiddleware(networkMiddleware, thunk))
  );
  isNetworkConnected(store).then(() => {
    callback(); // Notify our root component we are good to go, so that we can render our app
  });

  return store;
}
```

Now this works as I would have wanted it to, notify redux of the connection changes.

So now I am stuck on getting thunk actions to be added to the `actionQueue` for them to be re-dispatched once `isConnected` is `true` again.

These are my actions:

```javascript
export const ACTION_TEXT = "ACTION_TEXT";

export function setActionText(actionText = "hello") {
  return {
    type: ACTION_TEXT,
    payload: actionText,
    meta: {
      retry: true
    }
  };
}

export const fetchActionText = text => {
  function thunk(dispatch) {
    fetch("https://jsonplaceholder.typicode.com/posts", {
      method: "POST",
      body: JSON.stringify({
        title: text,
        body: "bar",
        userId: 1
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8"
      }
    })
      .then(response => response.json())
      .then(responseJson => {
        dispatch(setActionText(responseJson.title));
        console.warn("dispatch successfull");
      })
      .catch(error => {
        console.error("ERROR: ", error);
      });
  }

  thunk.interceptInOffline = true; // This is the important part
  return thunk; // Return it afterwards
};

fetchActionText.interceptInOffline = true; // In order to be intercepted by the middleware
fetchActionText.meta = {
  retry: true // By passing true, your thunk will be enqueued on offline mode
  // dismiss?: Array<string> // Array of actions which, once dispatched, will trigger a dismissal from the queue
};
```

Note that I'm guessing something is happening in the background since the `console.error()` in the `catch()` never gets called if I put the phone offline (airplane mode).

I was wondering what are the right steps to re-dispatch these actions that failed due to `isConnected` being `false`.

Thanks!

**EDIT**
After reading a few issues I encountered this https://github.com/rauliyohmc/react-native-offline/issues/48#issuecomment-342656168

I added:
```javascript
...
thunk.interceptInOffline = true; // This is the important part
thunk.meta = {
  retry: true
};
return thunk; // Return it afterwards
...
```

and now it places it in the `actionQueue` but as a `null` like this:

```
{"isConnected":true,"actionQueue":[null]}
```

I guess the question now would be, how to add failed thunk actions to `actionQueue`

**Comment by rauliyohmc** [comment]
Hi, are you using `redux-persist`?

If so, you may follow up on: https://github.com/rauliyohmc/react-native-offline/issues/35

**Comment by kanion** [comment]
Hi,
I have similar question... I managed to make it working with redux-thunk and redux-persist(I am using redux promise too), but when I go online actions are dispatched, but action queue in is not clearing.

my action is looking like that:
`export const exampleAction = (url) => {
    function thunk(dispatch) {
        // dispatch sometimes undefined?
        if(dispatch) {
            dispatch({
                type: types.SEND_REPLY,
                payload: new Promise((resolve, reject) => {
                    console.log('fetch');
                    fetch('https://www.google.com', {
                        method: 'GET',
                    })
                        .then(data => {
                            console.log('resolve');
                            resolve(data);
                        })
                        .catch((error) => {
                            console.log('reject');
                            reject(error);
                        });
                }),
            });
        }
    }

    thunk.interceptInOffline = true;
    thunk.meta = {
        name: 'exampleAction',
        args: [url], 
        retry: true
    };

    return thunk;
};`

**Comment by rgommezz** [comment]
Closing, since it's related to #35. Let's follow up on this one
