### ISSUE TITLE
Offline Queue with redux-saga not work?

### ISSUE THREAD

**Issue by ducpt2** [rgommezz/react-native-offline#85]
I am trying to set up a simple test with react-native-offline and redux, redux-saga. But offline queue seem like not work at all. Action not re-run when network re-connect. My config: 
- Give the network reducer to Redux.
- Fork networkEventsListenerSaga from your root saga.
- Access your network state in your components using mapStateToProps(), as state.network.isConnected  ===> It work, i can get isConnected value.
- create createNetworkMiddleware(), like your usage example (i am not pass Config to createNetworkMiddleware, just use it like your example).
- add meta: {  retry: true} in my action (and i am also try on my yield put(...meta: {  retry: true}))

=> And Offline Queue doesn't work, do i miss something? Can you point it out?
Thanks you.

**Comment by MehdiAlouafi** [comment]
Without any code samples it is hard to know what is going on. Can you provide for example and action that you want to be re-dispatched after the connection gets back ?

**Comment by rgommezz** [comment]
Without code examples I am afraid I am not able to help, sorry
