### ISSUE TITLE
react-native-navigation integration network state not changing

### ISSUE THREAD

**Issue by qasimalbaqali** [rgommezz/react-native-offline#87]
I followed https://github.com/rgommezz/react-native-offline/issues/12#issuecomment-303838827 for integrating the package with RNN, but the state of network isConnected doesn't seem to change when the network is turned off and then on. Also the default state as soon as the app is launched will always be true, and I noticed that it's not pinging the google server when it's offline.

Here is how I am setting it up.

```
import { reducer as network } from 'react-native-offline';

const appReducer = combineReducers({
    authentication,
    .....
    network
});
.....
```

```
import {connect} from "react-redux";
import {withNetworkConnectivity} from "react-native-offline";

export function registerScreens(store, Provider) {
    Navigation.registerComponent('rawag.Login', () => connect()(withNetworkConnectivity(false)(LoginScreen)), store, Provider);
    Navigation.registerComponent('rawag.Register', () => connect()(withNetworkConnectivity(false)(RegisterScreen)), store, Provider);
}
```

Any suggestions?

**Comment by rgommezz** [comment]
You are not using `withNetworkConnectivity` [correctly](https://github.com/rgommezz/react-native-offline#2a--wrap-your-top-most-react-component-into-withnetworkconnectivity-and-configure-it-with-withredux--true). It should be:

`withNetworkConnectivity({ withRedux: true })`

As an aside, you also don't need to use `connect()` in that file

**Comment by qasimalbaqali** [comment]
@rgommezz Thank you
