### ISSUE TITLE
Ability to check connectivity on action execution not regularly

### ISSUE THREAD

**Issue by repapa** [rgommezz/react-native-offline#91]
Hi @rgommezz,

Can we have a feature that it doesn't ping a URL regularly(using checkConnectionInterval) but instead it will just check/ping a URL once a specific action is executed?

**Comment by repapa** [comment]
Hi @rgommezz,

I would like to follow-up on this. :)

**Comment by rgommezz** [comment]
Hey @repapa,

[This pending PR](https://github.com/rgommezz/react-native-offline/pull/75) will add such functionality. However, it will work only if you are using redux-saga as middleware.

For other middleware such as thunks, there is no such functionality implemented

**Comment by repapa** [comment]
@rgommezz  thanks for the quick response. I'm using redux-saga and I'm looking forward to the pending PR. :)

**Comment by repapa** [comment]
Hi @rgommezz,

I saw the pending PR and in the commit they have:
![image](https://user-images.githubusercontent.com/19182530/40653526-0ad67d5e-636e-11e8-8440-065136d3ee3c.png)

With regards to the implementation of it once merged, should I call the action checkInternetAccess before I call my action that save the data in the queue when offline?

Ex.
![image](https://user-images.githubusercontent.com/19182530/40653743-a49b4690-636e-11e8-8513-20fa1572416a.png)

Additionally, will it still work if I remove networkEventsListenerSaga in my index saga?
![image](https://user-images.githubusercontent.com/19182530/40653858-09b8e834-636f-11e8-9da9-83ac99a88b13.png)

**Comment by rgommezz** [comment]
If you wanna opt out for checking regularly, just don't pass any `checkConnectionInterval` or pass `0`.

You still need to fork `networkEventsListenerSaga`. Then, by doing: `dispatch(checkInternetConnection())` it will fire a network check on demand
