### ISSUE TITLE
Connectivity after rehydration of store

### ISSUE THREAD

**Issue by dickerpulli** [rgommezz/react-native-offline#93]
Hi.

Couldn't you export the function checkInternetAccess() to allow to check connectivity the same way, your module does.

In the README(Miscellanea/FAQ) you describe how to dispatch CONNECTION_CHANGE on startup. Why is the code example implemented with NetInfo and not with your checkInternetAccess() function?

**Comment by rgommezz** [comment]
> In the README(Miscellanea/FAQ) you describe how to dispatch CONNECTION_CHANGE on startup. Why is the code example implemented with NetInfo and not with your checkInternetAccess() function?

My goal was to illustrate how to defer the rendering of your main screen until something _asynchronous_ happens, like checking internet connection. You are right it's implemented using pure `NetInfo` and that may mislead some people.

If you would like create a PR where `isNetworkConnected` is moved into a separated function, with the addition of the extra check by using the _private_ `checkInternetAccess`, that would be more than welcome. We could rename it to `checkInternetConnectionOnStartup`, export it as part of the public API and use it on the FAQ example.

Looking forward to hearing your thoughts!

**Comment by dickerpulli** [comment]
I have made a PR https://github.com/rgommezz/react-native-offline/pull/94

**Comment by joaopiopedreira** [comment]
Hi @rgommezz , my issue is somehow related to this one. For some reason, although the package and store configuration is correct, I cannot make your default `isConnected` mechanics to work in my use case. 

I'm using MeteorJS in the backend and [react-native-meteor](https://www.npmjs.com/package/react-native-meteor) in the front-end.

So my connection is a websocket from Meteor.

What I'm doing to detect a connection (and it's working fine) is the following:

```
  // Trigger online/offline mode manually, according to meteor connection state
  const isConnected = store.getState().network.isConnected;
  if(isConnectedToMeteor !== isConnected) {
    store.dispatch({type: '@@network-connectivity/CONNECTION_CHANGE',payload:isConnectedToMeteor});
    // dispatching queued actions in order of arrival (if we have any)
    if(isConnectedToMeteor) {
      const actionQueue = store.getState().network.actionQueue;
      if (actionQueue.length > 0) {
        actionQueue.forEach((action) => {
          if(action) {
            store.dispatch(action);
          }
        });
      }
    }
  }
```
where `isConnectedToMeteor` is a reactive variable (running in a reactive context) reading the connection state from Meteor and `isConnected` comes from your package.

I guess what I'd really like to know is if I'll run into issues by using this approach. What do you think?
